"""Static source definitions for official warning feeds."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class WarningSource:
    """Definition of one official warning source.

    ``country_code`` selects ordinary country-routed alert sources.  For a
    tropical-system source, ``issuer_country_code`` instead records the ISO
    3166-1 alpha-2 location of its operational issuing centre.  It is
    presentation metadata only: it must not be used to route or exclude
    tropical systems.
    """

    id: str
    name: str
    backend: str
    country_code: str | None
    url: str | None
    lang: str | None = None
    notes: str | None = None
    kind: str = 'alert'
    issuer_country_code: str | None = None


SOURCES: tuple[WarningSource, ...] = (
    WarningSource(
        id='swic_extreme',
        name='WMO Severe Weather Information Centre',
        backend='swic_extreme',
        country_code=None,
        url='https://severeweather.wmo.int/f/wfs',
        notes='Global WMO SWIC mapped Extreme-warning discovery feed. Coverage is limited to mapped participating providers; the dedicated query defaults to active, non-marine candidates.',
    ),
    WarningSource(
        id='nws',
        name='U.S. National Weather Service',
        backend='nws',
        country_code='US',
        url='https://api.weather.gov/alerts/active',
        lang='en',
        notes='Official NWS alerts API with native point queries.',
    ),
    WarningSource(
        id='ntwc_tsunami',
        name='NOAA National Tsunami Warning Center',
        backend='noaa_tsunami',
        country_code=None,
        url='https://www.tsunami.gov/events/xml/PAAQAtom.xml',
        lang='en',
        notes='Official NOAA NTWC Atom feed with linked CAP tsunami alerts.',
    ),
    WarningSource(
        id='ptwc_tsunami',
        name='NOAA Pacific Tsunami Warning Center',
        backend='noaa_tsunami',
        country_code=None,
        url='https://www.tsunami.gov/events/xml/PHEBCAP.xml',
        lang='en',
        notes='Official NOAA PTWC CAP tsunami alert endpoint.',
    ),
    WarningSource(
        id='nhc_gis_atlantic',
        name='NOAA National Hurricane Center',
        backend='nhc_gis',
        country_code=None,
        url='https://www.nhc.noaa.gov/gis-at.xml',
        lang='en',
        notes='Official NOAA NHC GIS RSS feed for active Atlantic tropical cyclones and associated storm GIS products.',
        kind='tropical_system',
        issuer_country_code='US',
    ),
    WarningSource(
        id='nhc_gis_eastern_pacific',
        name='NOAA National Hurricane Center',
        backend='nhc_gis',
        country_code=None,
        url='https://www.nhc.noaa.gov/gis-ep.xml',
        lang='en',
        notes='Official NOAA NHC GIS RSS feed for active Eastern Pacific tropical cyclones and associated storm GIS products.',
        kind='tropical_system',
        issuer_country_code='US',
    ),
    WarningSource(
        id='cphc_gis_central_pacific',
        name='NOAA Central Pacific Hurricane Center',
        backend='nhc_gis',
        country_code=None,
        url='https://www.nhc.noaa.gov/gis-cp.xml',
        lang='en',
        notes='Official NOAA CPHC GIS RSS feed for active Central Pacific tropical cyclones and associated storm GIS products.',
        kind='tropical_system',
        issuer_country_code='US',
    ),
    WarningSource(
        id='jma_tropical',
        name='Japan Meteorological Agency',
        backend='jma_tropical',
        country_code=None,
        url='https://www.data.jma.go.jp/developer/xml/feed/extra.xml',
        lang='ja',
        notes='Official JMA XML update feed, restricted to the dedicated VPTI50-52 and VPTW60-65 tropical-cyclone products; returns one latest report per system.',
        kind='tropical_system',
        issuer_country_code='JP',
    ),
    WarningSource(
        id='bom_tropical',
        name='Australian Bureau of Meteorology',
        backend='bom_tropical',
        country_code=None,
        url='ftp://ftp.bom.gov.au/anon/gen/fwo/',
        lang='en',
        notes='Official public BoM FTP tropical-cyclone forecast-track GML products for the Australian region. Includes a centre, track and, when issued, watch, warning, forecast and wind-area geometry.',
        kind='tropical_system',
        issuer_country_code='AU',
    ),
    WarningSource(
        id='hko_tropical',
        name='Hong Kong Observatory',
        backend='hko',
        country_code=None,
        url='https://www.weather.gov.hk/wxinfo/currwx/tc_list.xml',
        lang='en,zh',
        notes='Official HKO tropical-cyclone list and per-system track XML for systems within HKO’s published Northwest Pacific and South China Sea responsibility region. Includes current analysis, past positions and, when issued, forecast positions.',
        kind='tropical_system',
        issuer_country_code='HK',
    ),
    WarningSource(
        id='meteofrance_reunion_tropical',
        name='Météo-France La Réunion (RSMC)',
        backend='meteofrance_reunion_tropical',
        country_code=None,
        url='https://meteofrance.re/fr/cyclone',
        lang='fr',
        notes='Official Météo-France La Réunion RSMC current Southwest Indian Ocean cyclone data, obtained from the public site’s anonymous session-backed trajectory service. Includes analysed centre, intensity, wind and pressure data, plus the published track.',
        kind='tropical_system',
        issuer_country_code='RE',
    ),
    WarningSource(
        id='geomet',
        name='Environment Canada',
        backend='geomet',
        country_code='CA',
        url='https://api.weather.gc.ca/collections/weather-alerts/items',
        lang='en,fr',
        notes='Official GeoMet OGC API weather-alerts collection.',
    ),
    WarningSource(
        id='dwd_en',
        name='Deutscher Wetterdienst',
        backend='dwd',
        country_code='DE',
        url='https://www.dwd.de/DWD/warnungen/cap-feed/en/rss.xml',
        lang='en',
        notes='Official DWD CAP RSS feed with linked CAP 1.2 alerts.',
    ),
    WarningSource(
        id='dwd_de',
        name='Deutscher Wetterdienst',
        backend='dwd',
        country_code='DE',
        url='https://www.dwd.de/DWD/warnungen/cap-feed/de/rss.xml',
        lang='de',
        notes='Official DWD CAP RSS feed; catalogued separately from the English feed.',
    ),
    WarningSource(
        id='fmi_en',
        name='Finnish Meteorological Institute',
        backend='fmi',
        country_code='FI',
        url='https://alerts.fmi.fi/cap/feed/rss_en-GB.rss',
        lang='en',
        notes='Official FMI CAP RSS feed with linked multilingual CAP alerts.',
    ),
    WarningSource(
        id='fmi_fi',
        name='Finnish Meteorological Institute',
        backend='fmi',
        country_code='FI',
        url='https://alerts.fmi.fi/cap/feed/rss_fi-FI.rss',
        lang='fi',
        notes='Official FMI CAP RSS feed with linked multilingual CAP alerts.',
    ),
    WarningSource(
        id='fmi_sv',
        name='Finnish Meteorological Institute',
        backend='fmi',
        country_code='FI',
        url='https://alerts.fmi.fi/cap/feed/rss_sv-FI.rss',
        lang='sv',
        notes='Official FMI CAP RSS feed with linked multilingual CAP alerts.',
    ),
    WarningSource(
        id='met_no',
        name='MET Norway',
        backend='met_no',
        country_code='NO',
        url='https://alert.met.no/alerts',
        lang='en,no',
        notes='Official MET Norway warning feed with linked bilingual CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='nve',
        name='NVE',
        backend='nve',
        country_code='NO',
        url='https://cap.nve.no/',
        lang='en,no',
        notes='Official Norwegian Water Resources and Energy Directorate CAP feed with linked bilingual CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='igewe',
        name='Institute of GeoSciences, Energy, Water and Environment',
        backend='generic_cap',
        country_code='AL',
        url='https://cap-sources.s3.amazonaws.com/al-igewe-en/rss.xml',
        lang='en',
        notes='Official Albania CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='andma',
        name='National Disaster Management Authority',
        backend='generic_cap',
        country_code='AF',
        url='https://cap-sources.s3.amazonaws.com/af-andma-en/rss.xml',
        lang='en',
        notes='Official Afghanistan CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='inamet_en',
        name='National Institute of Hydrometeorology and Geophysics',
        backend='generic_cap',
        country_code='AO',
        url='https://cap-sources.s3.amazonaws.com/ao-inamet-en/rss.xml',
        lang='en',
        notes='Official Angola CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='lms_en',
        name='Lesotho Meteorological Services',
        backend='generic_cap',
        country_code='LS',
        url='https://cap-sources.s3.amazonaws.com/ls-lms-en/rss.xml',
        lang='en',
        notes='Official Lesotho CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='nmc_libya_en',
        name='National Meteorological Centre',
        backend='generic_cap',
        country_code='LY',
        url='https://cap-sources.s3.amazonaws.com/ly-nmc-en/rss.xml',
        lang='en',
        notes='Official Libya CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='vedur',
        name='Icelandic Meteorological Office',
        backend='vedur',
        country_code='IS',
        url='https://api.vedur.is/cap/v1/capbroker/active/feed/met',
        lang='en,is',
        notes='Official IMO CAP RSS feed with linked bilingual CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='bmkg_en',
        name='BMKG',
        backend='bmkg',
        country_code='ID',
        url='https://www.bmkg.go.id/alerts/nowcast/en',
        lang='en',
        notes='Official BMKG CAP RSS feed; downstream applications must credit BMKG as the data source.',
    ),
    WarningSource(
        id='bmkg_id',
        name='BMKG',
        backend='bmkg',
        country_code='ID',
        url='https://www.bmkg.go.id/alerts/nowcast/id',
        lang='id',
        notes='Official BMKG CAP RSS feed; downstream applications must credit BMKG as the data source.',
    ),
    WarningSource(
        id='smn',
        name='Servicio Meteorológico Nacional',
        backend='smn',
        country_code='AR',
        url='https://ssl.smn.gob.ar/CAP/AR.php',
        lang='es',
        notes='Official SMN Argentina CAP RSS feed with direct CAP alert links and polygon geometry.',
    ),
    WarningSource(
        id='dma_anguilla',
        name='Disaster Management Anguilla',
        backend='capews',
        country_code='AI',
        url='https://axa-primary.capews.com/capews/public/atom?type=cap',
        lang='en',
        notes='Official CAPEWS Atom feed for Anguilla with linked CAP alerts.',
    ),
    WarningSource(
        id='antigua_met',
        name='Antigua and Barbuda Meteorological Service',
        backend='capews',
        country_code='AG',
        url='https://atg-primary.capews.com/capews/public/atom?type=cap',
        lang='en',
        notes='Official CAPEWS Atom feed for Antigua and Barbuda with linked CAP alerts.',
    ),
    WarningSource(
        id='bahrain_en',
        name='Bahrain Meteorological Directorate',
        backend='bahrain',
        country_code='BH',
        url='https://cap-sources.s3.amazonaws.com/bh-meteo-en/rss.xml',
        lang='en',
        notes='Official Bahrain CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='bahrain_ar',
        name='Bahrain Meteorological Directorate',
        backend='bahrain',
        country_code='BH',
        url='https://cap-sources.s3.amazonaws.com/bh-meteo-ar/rss.xml',
        lang='ar',
        notes='Official Bahrain CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='bom',
        name='Bureau of Meteorology',
        backend='swic_mirror',
        country_code='AU',
        url='https://severeweather.wmo.int/v2/cap-alerts/au-bom-en/rss.xml',
        lang='en',
        notes='Official BoM public alert feed mirrored through the WMO Severe Weather Information Centre, with linked CAP XML alerts, packaged geocode geometry, and WMO map-geometry backfill only when needed.',
    ),
    WarningSource(
        id='belgidromet_en',
        name='Belgidromet',
        backend='belgidromet',
        country_code='BY',
        url='https://meteoalert.meteoinfo.ru/belarus/cap-feed/en/atom.xml',
        lang='en',
        notes='Official Belgidromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='belgidromet_ru',
        name='Belgidromet',
        backend='belgidromet',
        country_code='BY',
        url='https://meteoalert.meteoinfo.ru/belarus/cap-feed/ru/atom.xml',
        lang='ru',
        notes='Official Belgidromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='dem_barbados',
        name='Department of Emergency Management Barbados',
        backend='capews',
        country_code='BB',
        url='https://brb-primary.capews.com/capews/public/atom?type=cap',
        lang='en,fr,es',
        notes='Official CAPEWS Atom feed for Barbados with linked CAP alerts.',
    ),
    WarningSource(
        id='inmet',
        name='Instituto Nacional de Meteorologia',
        backend='inmet',
        country_code='BR',
        url='https://apiprevmet3.inmet.gov.br/avisos/rss',
        lang='pt-br',
        notes='Official INMET RSS feed whose item links resolve to CAP XML alerts with polygons and warning parameters.',
    ),
    WarningSource(
        id='nms_belize',
        name='Belize National Meteorological Service',
        backend='nms_belize',
        country_code='BZ',
        url='https://cap-sources.s3.amazonaws.com/bz-nms-en/rss.xml',
        lang='en',
        notes='Official Belize CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteobenin',
        name='METEO-BENIN',
        backend='meteobenin',
        country_code='BJ',
        url='https://www.meteobenin.bj/api/cap/rss.xml',
        lang='fr',
        notes='Official METEO-BENIN CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='dms_botswana',
        name='Botswana Department of Meteorological Services',
        backend='dms_botswana',
        country_code='BW',
        url='https://cap-sources.s3.amazonaws.com/bw-met-en/rss.xml',
        lang='en',
        notes='Official Botswana CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteoburkina',
        name='Agence Nationale de la Météorologie du Burkina Faso',
        backend='meteoburkina',
        country_code='BF',
        url='https://meteoburkina.bf/api/cap/rss.xml',
        lang='fr',
        notes='Official Burkina Faso CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='igebu',
        name='Institut Géographique du Burundi',
        backend='igebu',
        country_code='BI',
        url='https://www.igebu.bi/api/cap/rss.xml',
        lang='fr',
        notes='Official Burundi CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteo_cameroon_en',
        name='Cameroon Directorate of National Meteorology',
        backend='meteo_cameroon',
        country_code='CM',
        url='https://cap-sources.s3.amazonaws.com/cm-meteo-en/rss.xml',
        lang='en',
        notes='Official Cameroon CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteo_cameroon_fr',
        name='Cameroon Directorate of National Meteorology',
        backend='meteo_cameroon',
        country_code='CM',
        url='https://cap-sources.s3.amazonaws.com/cm-meteo-fr/rss.xml',
        lang='fr',
        notes='Official Cameroon CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='cma',
        name='China Meteorological Administration',
        backend='swic_mirror',
        country_code='CN',
        url='https://severeweather.wmo.int/v2/cap-alerts/cn-cma-xx/rss.xml',
        lang='en',
        notes='Official CMA public alert feed mirrored through the WMO Severe Weather Information Centre, with linked CAP XML alerts and WMO map-geometry backfill when CAP lacks polygons.',
    ),
    WarningSource(
        id='imn_costa_rica',
        name='Instituto Meteorológico Nacional',
        backend='generic_cap',
        country_code='CR',
        url='https://cap-sources.s3.amazonaws.com/cr-imn-es/rss.xml',
        lang='es',
        notes='Official Costa Rica CAP RSS feed distributed via the WMO Alert Hub mirror, with linked Spanish CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='dmn_car',
        name='Direction de la Météorologie Nationale',
        backend='generic_cap',
        country_code='CF',
        url='https://cap-sources.s3.amazonaws.com/cf-dmn-fr/rss.xml',
        lang='fr',
        notes='Official Central African Republic CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteotchad',
        name='Agence Nationale de la Météorologie du Tchad',
        backend='meteotchad',
        country_code='TD',
        url='https://www.meteotchad.org/api/cap/rss.xml',
        lang='fr',
        notes='Official Chad CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteochile',
        name='Dirección Meteorológica de Chile',
        backend='meteochile',
        country_code='CL',
        url='https://archivos.meteochile.gob.cl/portaldmc/rss/rss.php',
        lang='es',
        notes='Official MeteoChile CAP RSS feed with direct CAP XML links and polygon geometry.',
    ),
    WarningSource(
        id='meteocomores',
        name='Diréction de la Météorologie Nationale des Comores',
        backend='meteocomores',
        country_code='KM',
        url='https://meteocomores.km/api/cap/rss.xml',
        lang='fr',
        notes='Official Comoros CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='dirmet_cg',
        name='Direction de la Météorologie Nationale du Congo',
        backend='dirmet_cg',
        country_code='CG',
        url='https://dirmet.cg/api/cap/rss.xml',
        lang='fr',
        notes='Official Congo CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteordcongo',
        name='Météo RD Congo (METTELSAT)',
        backend='meteordcongo',
        country_code='CD',
        url='https://meteordcongo.cd/api/cap/rss.xml',
        lang='fr',
        notes='Official DR Congo CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='sodexam',
        name='SODEXAM',
        backend='generic_cap',
        country_code='CI',
        url='https://cap-sources.s3.amazonaws.com/ci-sodexam-fr/rss.xml',
        lang='fr',
        notes="Official Côte d'Ivoire CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.",
    ),
    WarningSource(
        id='meteodjibouti',
        name='Agence Nationale de la Météorologie de Djibouti',
        backend='meteodjibouti',
        country_code='DJ',
        url='https://meteodjibouti.dj/api/cap/rss.xml',
        lang='fr',
        notes='Official Djibouti CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='ema_egypt',
        name='Egyptian Meteorological Authority',
        backend='generic_cap',
        country_code='EG',
        url='https://cap-sources.s3.amazonaws.com/eg-ema-en/rss.xml',
        lang='en',
        notes='Official Egyptian Meteorological Authority CAP RSS feed distributed via the WMO Alert Hub mirror, with linked English CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='ethiomet',
        name='Ethiopian Meteorology Institute',
        backend='ethiomet',
        country_code='ET',
        url='https://www.ethiomet.gov.et/api/cap/rss.xml',
        lang='en',
        notes='Official Ethiopian Meteorology Institute CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteogambia',
        name='Department of Water Resources, The Gambia',
        backend='meteogambia',
        country_code='GM',
        url='https://meteogambia.gm/api/cap/rss.xml',
        lang='en',
        notes='Official Gambia CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='dgm_gabon',
        name='Direction Generale de la Météorologie',
        backend='generic_cap',
        country_code='GA',
        url='https://cap-sources.s3.amazonaws.com/ga-dgm-fr/rss.xml',
        lang='fr',
        notes='Official Gabon CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='gmet',
        name='Ghana Meteorological Agency',
        backend='gmet',
        country_code='GH',
        url='https://www.meteo.gov.gh/api/cap/rss.xml',
        lang='en',
        notes='Official Ghana CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='anmeteo',
        name='Agence Nationale de la Météorologie',
        backend='anmeteo',
        country_code='GN',
        url='https://anmeteo.gov.gn/api/cap/rss.xml',
        lang='fr',
        notes='Official Guinea CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteoguinebissau',
        name='Instituto Nacional de Meteorologia da Guine-Bissau',
        backend='meteoguinebissau',
        country_code='GW',
        url='https://meteoguinebissau.gw/api/cap/rss.xml',
        lang='pt',
        notes='Official Guinea-Bissau CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='hydromet_guyana',
        name='HydroMet Guyana',
        backend='hydromet_guyana',
        country_code='GY',
        url='https://cap-sources.s3.amazonaws.com/gy-hms-en/rss.xml',
        lang='en',
        notes='Official Guyana CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='dmh_py',
        name='Dirección de Meteorología e Hidrología',
        backend='dmh_py',
        country_code='PY',
        url='https://cap-sources.s3.amazonaws.com/py-dmh-es/rss.xml',
        lang='es',
        notes='Official Paraguay CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='qatar_caa_en',
        name='Qatar Civil Aviation Authority',
        backend='qatar_caa',
        country_code='QA',
        url='https://cap-sources.s3.amazonaws.com/qa-caa-en/rss.xml',
        lang='en',
        notes='Official Qatar CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='qatar_caa_ar',
        name='Qatar Civil Aviation Authority',
        backend='qatar_caa',
        country_code='QA',
        url='https://cap-sources.s3.amazonaws.com/qa-caa-ar/rss.xml',
        lang='ar',
        notes='Official Qatar CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='imd_india',
        name='India Meteorological Department',
        backend='imd_india',
        country_code='IN',
        url='https://cap-sources.s3.amazonaws.com/in-imd-en/rss.xml',
        lang='en',
        notes='Official India Meteorological Department CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='irimo_en',
        name='Iran Meteorological Organization',
        backend='generic_cap',
        country_code='IR',
        url='https://cap-sources.s3.amazonaws.com/ir-irimo-en/rss.xml',
        lang='en',
        notes='Official Iran Meteorological Organization CAP RSS feed distributed via the WMO Alert Hub mirror, with linked English CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='jma',
        name='Japan Meteorological Agency',
        backend='jma',
        country_code='JP',
        url='https://www.data.jma.go.jp/developer/xml/feed/extra.xml',
        lang='ja',
        notes='Official JMA public Atom feed for XML bulletins; first cut focuses on VPWW53 and newer weather warning/advisory products.',
    ),
    WarningSource(
        id='met_eireann',
        name='Met Eireann',
        backend='met_eireann',
        country_code='IE',
        url='https://www.met.ie/warningsxml/rss.xml',
        lang='en',
        notes='Official Met Eireann CAP RSS feed with direct CAP XML links, EMMA geocodes, and awareness parameters.',
    ),
    WarningSource(
        id='jmd_en',
        name='Jordan Meteorological Department',
        backend='jmd',
        country_code='JO',
        url='https://cap-sources.s3.amazonaws.com/jo-meteo-en/rss.xml',
        lang='en',
        notes='Official Jordan CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='jmd_ar',
        name='Jordan Meteorological Department',
        backend='jmd',
        country_code='JO',
        url='https://cap-sources.s3.amazonaws.com/jo-meteo-ar/rss.xml',
        lang='ar',
        notes='Official Jordan CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='msj',
        name='Meteorological Service of Jamaica',
        backend='msj',
        country_code='JM',
        url='https://alert.metservice.gov.jm/capfeed.php',
        lang='en',
        notes='Official Meteorological Service of Jamaica CAP Atom feed with linked CAP XML alerts.',
    ),
    WarningSource(
        id='meteo_madagascar_en',
        name='Operational Meteorology',
        backend='generic_cap',
        country_code='MG',
        url='https://cap-sources.s3.amazonaws.com/mg-meteo-en/rss.xml',
        lang='en',
        notes='Official Madagascar CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='dmh_myanmar',
        name='Department of Meteorology and Hydrology Myanmar',
        backend='dmh_myanmar',
        country_code='MM',
        url='https://feeds-dmh.zamg.ac.at/feeds/dmh-warnings',
        lang='en',
        notes='Official DMH Myanmar Atom warnings feed with linked CAP alerts.',
    ),
    WarningSource(
        id='mss_singapore',
        name='Meteorological Service Singapore',
        backend='generic_cap',
        country_code='SG',
        url='https://www.weather.gov.sg/files/rss/rsscapalert/rsscapalert.xml',
        lang='en',
        notes='Official public-domain Singapore CAP RSS feed with linked English warning documents and polygon geometry.',
    ),
    WarningSource(
        id='met_oman_en',
        name='Directorate General of Meteorology',
        backend='generic_cap',
        country_code='OM',
        url='https://cap-sources.s3.amazonaws.com/om-met-en/rss.xml',
        lang='en',
        notes='Official Oman CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='tuvmet',
        name='Tuvalu Meteorological Service',
        backend='generic_cap',
        country_code='TV',
        url='https://cap-sources.s3.amazonaws.com/tv-tuvmet-en/rss.xml',
        lang='en',
        notes='Official Tuvalu CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteo_ke',
        name='Kenya Meteorological Department',
        backend='meteo_ke',
        country_code='KE',
        url='https://meteo.go.ke/api/cap/rss.xml',
        lang='en',
        notes='Official Kenya Meteorological Department CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='kma',
        name='Korea Meteorological Administration',
        backend='kma',
        country_code='KR',
        url='https://www.weather.go.kr/w/rss/cap/warning.do',
        lang='en',
        notes='Official Korea Meteorological Administration CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='kuwait_met',
        name='Kuwait Meteorological Department',
        backend='generic_cap',
        country_code='KW',
        url='https://www.met.gov.kw/rss_eng/kuwait_cap.xml',
        lang='en',
        notes='Official Kuwait Meteorological Department CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='kyrgyzhydromet_en',
        name='Kyrgyzhydromet',
        backend='kyrgyzhydromet',
        country_code='KG',
        url='https://meteoalert.meteoinfo.ru/kyrgyzstan/cap-feed/en/atom.xml',
        lang='en',
        notes='Official Kyrgyzhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='kyrgyzhydromet_ru',
        name='Kyrgyzhydromet',
        backend='kyrgyzhydromet',
        country_code='KG',
        url='https://meteoalert.meteoinfo.ru/kyrgyzstan/cap-feed/ru/atom.xml',
        lang='ru',
        notes='Official Kyrgyzhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteoliberia',
        name='Liberia Meteorological Service',
        backend='meteoliberia',
        country_code='LR',
        url='https://meteoliberia.com/api/cap/rss.xml',
        lang='en',
        notes='Official Liberia Meteorological Service CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='smg',
        name='Macao Meteorological and Geophysical Bureau',
        backend='smg',
        country_code='MO',
        url='https://rss.smg.gov.mo/cap_rss.xml',
        lang='en,zh,pt',
        notes='Official Macao CAP RSS feed with linked multilingual CAP XML alerts and polygon geometry.',
    ),
    WarningSource(
        id='metmalawi',
        name='Department of Climate Change and Meteorological Services',
        backend='metmalawi',
        country_code='MW',
        url='https://www.metmalawi.gov.mw/api/cap/rss.xml',
        lang='en',
        notes='Official Malawi CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='mms',
        name='Maldives Meteorological Service',
        backend='mms',
        country_code='MV',
        url='https://cap.meteorology.gov.mv/rss/alerts/',
        lang='en',
        notes='Official Maldives CAP RSS feed with linked CAP XML alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteomauritanie',
        name='Office National de la Météorologie',
        backend='meteomauritanie',
        country_code='MR',
        url='https://meteomauritanie.mr/api/cap/rss.xml',
        lang='fr',
        notes='Official Mauritania CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='namem_en',
        name='National Agency for Meteorology and Environmental Monitoring',
        backend='namem',
        country_code='MN',
        url='https://cap-sources.s3.amazonaws.com/mn-namem-en/rss.xml',
        lang='en',
        notes='Official Mongolia CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='inam_mz',
        name='Instituto Nacional de Meteorologia',
        backend='inam_mz',
        country_code='MZ',
        url='https://cap-sources.s3.amazonaws.com/mz-inam-pt/rss.xml',
        lang='pt',
        notes='Official Mozambique CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='nimet_en',
        name='Nigerian Meteorological Agency',
        backend='nimet',
        country_code='NG',
        url='https://cap-sources.s3.amazonaws.com/ng-nimet-en/rss.xml',
        lang='en',
        notes='Official Nigeria CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='kazhydromet_en',
        name='Kazhydromet',
        backend='kazhydromet',
        country_code='KZ',
        url='https://meteoalert.meteoinfo.ru/kazakhstan/cap-feed/en/atom.xml',
        lang='en',
        notes='Official Kazhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='kazhydromet_ru',
        name='Kazhydromet',
        backend='kazhydromet',
        country_code='KZ',
        url='https://meteoalert.meteoinfo.ru/kazakhstan/cap-feed/ru/atom.xml',
        lang='ru',
        notes='Official Kazhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='hydrometcenter_en',
        name='Hydrometcenter of Russia',
        backend='hydrometcenter',
        country_code='RU',
        url='https://meteoinfo.ru/hmc-output/cap/cap-feed/en/atom.xml',
        lang='en',
        notes='Official Hydrometcenter of Russia CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='hydrometcenter_ru',
        name='Hydrometcenter of Russia',
        backend='hydrometcenter',
        country_code='RU',
        url='https://meteoinfo.ru/hmc-output/cap/cap-feed/ru/atom.xml',
        lang='ru',
        notes='Official Hydrometcenter of Russia CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='hko',
        name='Hong Kong Observatory',
        backend='hko',
        country_code='HK',
        url='https://alerts.weather.gov.hk/V1/cap_atom.xml',
        lang='en,zh',
        notes='Official Hong Kong Observatory CAP Atom feed with linked CAP XML alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteo_sc',
        name='Seychelles Meteorological Authority',
        backend='meteo_sc',
        country_code='SC',
        url='https://www.meteo.sc/api/cap/rss.xml',
        lang='en',
        notes='Official Seychelles Meteorological Authority CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='slmet',
        name='Sierra Leone Meteorological Agency',
        backend='slmet',
        country_code='SL',
        url='https://slmet.gov.sl/api/cap/rss.xml',
        lang='en',
        notes='Official Sierra Leone Meteorological Agency CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='solomon_met',
        name='Solomon Islands Meteorological Service',
        backend='solomon_met',
        country_code='SB',
        url='https://cap-sources.s3.amazonaws.com/sb-met-en/rss.xml',
        lang='en',
        notes='Official Solomon Islands CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteosouthsudan',
        name='South Sudan Meteorological Services',
        backend='meteosouthsudan',
        country_code='SS',
        url='https://meteosouthsudan.com.ss/api/cap/rss.xml',
        lang='en',
        notes='Official South Sudan Meteorological Services CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='aemet',
        name='AEMET',
        backend='aemet',
        country_code='ES',
        url='https://www.aemet.es/documentos_d/eltiempo/prediccion/avisos/rss/CAP_AFAE_wah_RSS.xml',
        lang='es,en',
        notes='Official AEMET CAP RSS feed with linked CAP XML, bilingual CAP info blocks, and polygon geometry.',
    ),
    WarningSource(
        id='meteosudan',
        name='Sudan Meteorological Authority',
        backend='meteosudan',
        country_code='SD',
        url='https://meteosudan.sd/api/cap/rss.xml',
        lang='ar',
        notes='Official Sudan Meteorological Authority CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteotogo',
        name='METEO TOGO (ANAMET)',
        backend='meteotogo',
        country_code='TG',
        url='https://meteotogo.tg/api/cap/rss.xml',
        lang='fr',
        notes='Official METEO TOGO (ANAMET) CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='anacim',
        name="Agence Nationale de l'Aviation Civile et de la Météorologie",
        backend='generic_cap',
        country_code='SN',
        url='https://cap-sources.s3.amazonaws.com/sn-anacim-fr/rss.xml',
        lang='fr',
        notes='Official Senegal CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='inmeteo_stp',
        name='Instituto Nacional de Meteorologia',
        backend='generic_cap',
        country_code='ST',
        url='https://cap-sources.s3.amazonaws.com/st-meteo-pt/rss.xml',
        lang='pt',
        notes='Official São Tomé and Príncipe CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='inm_tunisia_en',
        name='National Institute of Meteorology',
        backend='generic_cap',
        country_code='TN',
        url='https://cap-sources.s3.amazonaws.com/tn-meteo-en/rss.xml',
        lang='en',
        notes='Official Tunisia CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='ttms',
        name='Trinidad and Tobago Meteorological Service',
        backend='ttms',
        country_code='TT',
        url='https://metproducts.gov.tt/ttms/public/api/feed?type=rss',
        lang='en',
        notes='Official Trinidad and Tobago Meteorological Service CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='tci_en',
        name='TCI Emergency Alerts',
        backend='tci',
        country_code='TC',
        url='https://cap-sources.s3.amazonaws.com/tc-gov-en/rss.xml',
        lang='en',
        notes='Official Turks and Caicos Islands CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and mixed polygon/circle geometry.',
    ),
    WarningSource(
        id='tci_ht',
        name='TCI Emergency Alerts',
        backend='tci',
        country_code='TC',
        url='https://cap-sources.s3.amazonaws.com/tc-gov-ht/rss.xml',
        lang='ht',
        notes='Official Turks and Caicos Islands CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and mixed polygon/circle geometry.',
    ),
    WarningSource(
        id='tci_es',
        name='TCI Emergency Alerts',
        backend='tci',
        country_code='TC',
        url='https://cap-sources.s3.amazonaws.com/tc-gov-es/rss.xml',
        lang='es',
        notes='Official Turks and Caicos Islands CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and mixed polygon/circle geometry.',
    ),
    WarningSource(
        id='svg_met',
        name='Saint Vincent and the Grenadines Meteorological Services',
        backend='capews',
        country_code='VC',
        url='https://vct-primary.capews.com/capews/public/atom?type=cap',
        lang='en',
        notes='Official CAPEWS Atom feed for Saint Vincent and the Grenadines with linked CAP alerts.',
    ),
    WarningSource(
        id='tmd_en',
        name='Thai Meteorological Department',
        backend='tmd',
        country_code='TH',
        url='https://www.tmd.go.th/en/api/xml/CAP',
        lang='en',
        notes='Official Thai Meteorological Department CAP RSS feed with linked CAP XML alerts and polygon geometry.',
    ),
    WarningSource(
        id='tmd_th',
        name='Thai Meteorological Department',
        backend='tmd',
        country_code='TH',
        url='https://www.tmd.go.th/api/xml/CAP',
        lang='th',
        notes='Official Thai Meteorological Department CAP RSS feed with linked CAP XML alerts and polygon geometry.',
    ),
    WarningSource(
        id='tma_en',
        name='Tanzania Meteorological Authority',
        backend='tma',
        country_code='TZ',
        url='https://cap-sources.s3.amazonaws.com/tz-tma-en/rss.xml',
        lang='en',
        notes='Official Tanzania Meteorological Authority CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='tma_sw',
        name='Tanzania Meteorological Authority',
        backend='tma',
        country_code='TZ',
        url='https://cap-sources.s3.amazonaws.com/tz-tma-sw/rss.xml',
        lang='sw',
        notes='Official Tanzania Meteorological Authority CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='inumet',
        name='Instituto Uruguayo de Meteorología',
        backend='inumet',
        country_code='UY',
        url='https://www.inumet.gub.uy/reportes/riesgo/rss.xml',
        lang='es',
        notes='Official INUMET CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='uzhydromet_en',
        name='Uzhydromet',
        backend='uzhydromet',
        country_code='UZ',
        url='https://meteoalert.meteoinfo.ru/uzbekistan/cap-feed/en/atom.xml',
        lang='en',
        notes='Official Uzhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='uzhydromet_ru',
        name='Uzhydromet',
        backend='uzhydromet',
        country_code='UZ',
        url='https://meteoalert.meteoinfo.ru/uzbekistan/cap-feed/ru/atom.xml',
        lang='ru',
        notes='Official Uzhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='vmgd',
        name='Vanuatu Meteorology and Geo-Hazards Department',
        backend='vmgd',
        country_code='VU',
        url='https://cap-sources.s3.amazonaws.com/vu-vmgd-en/rss.xml',
        lang='en',
        notes='Official Vanuatu Meteorology and Geo-Hazards Department CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='zmd',
        name='Zambia Meteorological Department',
        backend='zmd',
        country_code='ZM',
        url='https://zmd.gov.zm/api/cap/rss.xml',
        lang='en',
        notes='Official Zambia Meteorological Department CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='weatherzw',
        name='Meteorological Services Department of Zimbabwe',
        backend='weatherzw',
        country_code='ZW',
        url='https://www.weatherzw.org.zw/api/cap/rss.xml',
        lang='en',
        notes='Official Meteorological Services Department of Zimbabwe CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='saint_lucia',
        name='Saint Lucia Meteorological Service',
        backend='saint_lucia',
        country_code='LC',
        url='https://saint-lucia.cap-composer.wiscaribbeancmo.org/api/cap/rss.xml',
        lang='en',
        notes='Official Saint Lucia CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='indomet',
        name='Instituto Dominicano de Meteorología',
        backend='indomet',
        country_code='DO',
        url='https://cap-sources.s3.amazonaws.com/do-indomet-es/rss.xml',
        lang='es',
        notes='Official Dominican Republic CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='inamhi',
        name='Instituto Nacional de Meteorología e Hidrología',
        backend='inamhi',
        country_code='EC',
        url='https://cap-sources.s3.amazonaws.com/ec-inamhi-es/rss.xml',
        lang='es',
        notes='Official Ecuador CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='eswatini_met',
        name='Eswatini Meteorological Service',
        backend='eswatini_met',
        country_code='SZ',
        url='https://cap-sources.s3.amazonaws.com/sz-met-en/rss.xml',
        lang='en',
        notes='Official Eswatini CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteo_cw_en',
        name='Meteorological Department Curaçao',
        backend='meteo_cw',
        country_code='CW',
        url='https://www.meteo.cw/rss/CAP_en.xml',
        lang='en',
        notes='Official Curaçao CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteo_cw_nl',
        name='Meteorological Department Curaçao',
        backend='meteo_cw',
        country_code='CW',
        url='https://www.meteo.cw/rss/CAP_nl.xml',
        lang='nl',
        notes='Official Curaçao CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteo_cw_pap',
        name='Meteorological Department Curaçao',
        backend='meteo_cw',
        country_code='CW',
        url='https://www.meteo.cw/rss/CAP_pap.xml',
        lang='pap',
        notes='Official Curaçao CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='metservice_nz',
        name='MetService New Zealand',
        backend='metservice_nz',
        country_code='NZ',
        url='https://alerts.metservice.com/cap/rss',
        lang='en',
        notes='Official MetService public CAP alert RSS feed.',
    ),
    WarningSource(
        id='meteo_suriname_en',
        name='Suriname Meteorological Service',
        backend='generic_cap',
        country_code='SR',
        url='https://cap-sources.s3.amazonaws.com/sr-meteo-en/rss.xml',
        lang='en',
        notes='Official Suriname CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='mms_mauritius',
        name='Mauritius Meteorological Services',
        backend='generic_cap',
        country_code='MU',
        url='https://cap-sources.s3.amazonaws.com/mu-mms-en/rss.xml',
        lang='en',
        notes='Official Mauritius CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='dnmg_timor_en',
        name='National Directorate of Meteorology and Geophysics',
        backend='generic_cap',
        country_code='TL',
        url='https://cap-sources.s3.amazonaws.com/tl-dnmg-en/rss.xml',
        lang='en',
        notes='Official Timor-Leste CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='smn_mexico',
        name='Servicio Meteorológico Nacional de México',
        backend='smn_mexico',
        country_code='MX',
        url='https://smn.conagua.gob.mx/tools/PHP/feedsmn/cap.php',
        lang='es',
        notes='Official SMN Mexico CAP Atom feed with direct CAP XML links and warning parameters.',
    ),
    WarningSource(
        id='imhpa',
        name='IMHPA',
        backend='generic_cap',
        country_code='PA',
        url='https://cap-sources.s3.amazonaws.com/pa-imhpa-es/rss.xml',
        lang='es',
        notes='Official Panama CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='pmd_pakistan',
        name='Pakistan Meteorological Department',
        backend='generic_cap',
        country_code='PK',
        url='https://cap-sources.s3.amazonaws.com/pk-pmd-en/rss.xml',
        lang='en',
        notes='Official Pakistan Meteorological Department CAP RSS feed distributed via the WMO Alert Hub mirror, with linked English CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='pagasa',
        name='PAGASA',
        backend='pagasa',
        country_code='PH',
        url='https://publicalert.pagasa.dost.gov.ph/feeds/',
        lang='en',
        notes='Official PAGASA Atom alert feed with linked CAP alerts.',
    ),
    WarningSource(
        id='meteoalarm_atom_andorra',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='AD',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-andorra',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_austria',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='AT',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-austria',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_belgium',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='BE',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-belgium',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_bosnia_herzegovina',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='BA',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-bosnia-herzegovina',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_bulgaria',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='BG',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-bulgaria',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_croatia',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='HR',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-croatia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_cyprus',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='CY',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-cyprus',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_czechia',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='CZ',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-czechia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_denmark',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='DK',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-denmark',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_estonia',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='EE',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-estonia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_france',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='FR',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-france',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_greece',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='GR',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-greece',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_hungary',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='HU',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-hungary',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_israel',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='IL',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-israel',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_italy',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='IT',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-italy',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_latvia',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='LV',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-latvia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_lithuania',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='LT',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-lithuania',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_luxembourg',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='LU',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-luxembourg',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_malta',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='MT',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-malta',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_montenegro',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='ME',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-montenegro',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_netherlands',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='NL',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-netherlands',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_north_macedonia',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='MK',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-republic-of-north-macedonia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_poland',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='PL',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-poland',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_portugal',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='PT',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-portugal',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_moldova',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='MD',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-moldova',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_romania',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='RO',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-romania',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_serbia',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='RS',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-serbia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_slovakia',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='SK',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-slovakia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_slovenia',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='SI',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-slovenia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_sweden',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='SE',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-sweden',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_switzerland',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='CH',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-switzerland',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and verified polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_united_kingdom',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='GB',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-united-kingdom',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='ea_flood',
        name='UK Environment Agency',
        backend='ea_flood',
        country_code='GB',
        url='https://environment.data.gov.uk/flood-monitoring/id/floods',
        lang='en',
        notes='Official UK Environment Agency flood warnings API for England with linked flood-area polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_ukraine',
        name='Meteoalarm',
        backend='meteoalarm_atom',
        country_code='UA',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-ukraine',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and verified MultiPolygon geometry.',
    ),
)

SOURCE_BY_ID = {source.id: source for source in SOURCES}
