"""Static source definitions for official warning feeds."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class WarningSource:
    """Definition of one official warning source."""

    id: str
    name: str
    backend: str
    country_code: str | None
    url: str | None
    lang: str | None = None
    notes: str | None = None
    provider_v2: bool = False


SOURCES: tuple[WarningSource, ...] = (
    WarningSource(
        id='nws',
        name='U.S. National Weather Service',
        backend='nws',
        country_code='US',
        url='https://api.weather.gov/alerts/active',
        lang='en',
        notes='Official NWS alerts API with native point queries.',
        provider_v2=True,
    ),
    WarningSource(
        id='geomet',
        name='Environment Canada GeoMet',
        backend='geomet',
        country_code='CA',
        url='https://api.weather.gc.ca/collections/weather-alerts/items',
        lang='en,fr',
        notes='Official GeoMet OGC API weather-alerts collection.',
        provider_v2=True,
    ),
    WarningSource(
        id='dwd_en',
        name='Deutscher Wetterdienst CAP Feed (English)',
        backend='dwd',
        country_code='DE',
        url='https://www.dwd.de/DWD/warnungen/cap-feed/en/rss.xml',
        lang='en',
        notes='Official DWD CAP RSS feed with linked CAP 1.2 alerts.',
        provider_v2=True,
    ),
    WarningSource(
        id='dwd_de',
        name='Deutscher Wetterdienst CAP Feed (German)',
        backend='dwd',
        country_code='DE',
        url='https://www.dwd.de/DWD/warnungen/cap-feed/de/rss.xml',
        lang='de',
        notes='Official DWD CAP RSS feed; catalogued separately from the English feed.',
        provider_v2=True,
    ),
    WarningSource(
        id='fmi_en',
        name='Finnish Meteorological Institute CAP Feed (English)',
        backend='fmi',
        country_code='FI',
        url='https://alerts.fmi.fi/cap/feed/rss_en-GB.rss',
        lang='en',
        notes='Official FMI CAP RSS feed with linked multilingual CAP alerts.',
        provider_v2=True,
    ),
    WarningSource(
        id='fmi_fi',
        name='Finnish Meteorological Institute CAP Feed (Finnish)',
        backend='fmi',
        country_code='FI',
        url='https://alerts.fmi.fi/cap/feed/rss_fi-FI.rss',
        lang='fi',
        notes='Official FMI CAP RSS feed with linked multilingual CAP alerts.',
        provider_v2=True,
    ),
    WarningSource(
        id='fmi_sv',
        name='Finnish Meteorological Institute CAP Feed (Swedish)',
        backend='fmi',
        country_code='FI',
        url='https://alerts.fmi.fi/cap/feed/rss_sv-FI.rss',
        lang='sv',
        notes='Official FMI CAP RSS feed with linked multilingual CAP alerts.',
        provider_v2=True,
    ),
    WarningSource(
        id='met_no',
        name='MET Norway MetAlerts CAP Feed',
        backend='met_no',
        country_code='NO',
        url='https://alert.met.no/alerts',
        lang='en,no',
        notes='Official MET Norway warning feed with linked bilingual CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='nve',
        name='NVE CAP Feed',
        backend='nve',
        country_code='NO',
        url='https://cap.nve.no/',
        lang='en,no',
        notes='Official Norwegian Water Resources and Energy Directorate CAP feed with linked bilingual CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='igewe',
        name='Institute of GeoSciences, Energy, Water and Environment CAP Feed',
        backend='generic_cap',
        country_code='AL',
        url='https://cap-sources.s3.amazonaws.com/al-igewe-en/rss.xml',
        lang='en',
        notes='Official Albania CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='andma',
        name='National Disaster Management Authority CAP Feed',
        backend='generic_cap',
        country_code='AF',
        url='https://cap-sources.s3.amazonaws.com/af-andma-en/rss.xml',
        lang='en',
        notes='Official Afghanistan CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='inamet_en',
        name='National Institute of Hydrometeorology and Geophysics CAP Feed (English)',
        backend='generic_cap',
        country_code='AO',
        url='https://cap-sources.s3.amazonaws.com/ao-inamet-en/rss.xml',
        lang='en',
        notes='Official Angola CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='lms_en',
        name='Lesotho Meteorological Services CAP Feed (English)',
        backend='generic_cap',
        country_code='LS',
        url='https://cap-sources.s3.amazonaws.com/ls-lms-en/rss.xml',
        lang='en',
        notes='Official Lesotho CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='nmc_libya_en',
        name='National Meteorological Centre CAP Feed (English)',
        backend='generic_cap',
        country_code='LY',
        url='https://cap-sources.s3.amazonaws.com/ly-nmc-en/rss.xml',
        lang='en',
        notes='Official Libya CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='vedur',
        name='Icelandic Meteorological Office CAP Feed',
        backend='vedur',
        country_code='IS',
        url='https://api.vedur.is/cap/v1/capbroker/active/feed/met',
        lang='en,is',
        notes='Official IMO CAP RSS feed with linked bilingual CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='bmkg_en',
        name='BMKG Nowcast CAP Feed (English)',
        backend='bmkg',
        country_code='ID',
        url='https://www.bmkg.go.id/alerts/nowcast/en',
        lang='en',
        notes='Official BMKG CAP RSS feed; downstream applications must credit BMKG as the data source.',
        provider_v2=True,
    ),
    WarningSource(
        id='bmkg_id',
        name='BMKG Nowcast CAP Feed (Indonesian)',
        backend='bmkg',
        country_code='ID',
        url='https://www.bmkg.go.id/alerts/nowcast/id',
        lang='id',
        notes='Official BMKG CAP RSS feed; downstream applications must credit BMKG as the data source.',
        provider_v2=True,
    ),
    WarningSource(
        id='smn',
        name='Servicio Meteorológico Nacional CAP Feed',
        backend='smn',
        country_code='AR',
        url='https://ssl.smn.gob.ar/CAP/AR.php',
        lang='es',
        notes='Official SMN Argentina CAP RSS feed with direct CAP alert links and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='dma_anguilla',
        name='Disaster Management Anguilla CAP Feed',
        backend='capews',
        country_code='AI',
        url='https://axa-primary.capews.com/capews/public/atom?type=cap',
        lang='en',
        notes='Official CAPEWS Atom feed for Anguilla with linked CAP alerts.',
        provider_v2=True,
    ),
    WarningSource(
        id='antigua_met',
        name='Antigua and Barbuda Meteorological Service CAP Feed',
        backend='capews',
        country_code='AG',
        url='https://atg-primary.capews.com/capews/public/atom?type=cap',
        lang='en',
        notes='Official CAPEWS Atom feed for Antigua and Barbuda with linked CAP alerts.',
        provider_v2=True,
    ),
    WarningSource(
        id='bahrain_en',
        name='Bahrain Meteorological Directorate CAP Feed (English)',
        backend='bahrain',
        country_code='BH',
        url='https://cap-sources.s3.amazonaws.com/bh-meteo-en/rss.xml',
        lang='en',
        notes='Official Bahrain CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='bahrain_ar',
        name='Bahrain Meteorological Directorate CAP Feed (Arabic)',
        backend='bahrain',
        country_code='BH',
        url='https://cap-sources.s3.amazonaws.com/bh-meteo-ar/rss.xml',
        lang='ar',
        notes='Official Bahrain CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='bom',
        name='Bureau of Meteorology CAP Feed',
        backend='swic_mirror',
        country_code='AU',
        url='https://severeweather.wmo.int/v2/cap-alerts/au-bom-en/rss.xml',
        lang='en',
        notes='Official BoM public alert feed mirrored through the WMO Severe Weather Information Centre, with linked CAP XML alerts.',
        provider_v2=True,
    ),
    WarningSource(
        id='belgidromet_en',
        name='Belgidromet CAP Feed (English)',
        backend='belgidromet',
        country_code='BY',
        url='https://meteoalert.meteoinfo.ru/belarus/cap-feed/en/atom.xml',
        lang='en',
        notes='Official Belgidromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='belgidromet_ru',
        name='Belgidromet CAP Feed (Russian)',
        backend='belgidromet',
        country_code='BY',
        url='https://meteoalert.meteoinfo.ru/belarus/cap-feed/ru/atom.xml',
        lang='ru',
        notes='Official Belgidromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='dem_barbados',
        name='Department of Emergency Management Barbados CAP Feed',
        backend='capews',
        country_code='BB',
        url='https://brb-primary.capews.com/capews/public/atom?type=cap',
        lang='en,fr,es',
        notes='Official CAPEWS Atom feed for Barbados with linked CAP alerts.',
        provider_v2=True,
    ),
    WarningSource(
        id='inmet',
        name='Instituto Nacional de Meteorologia CAP Feed',
        backend='inmet',
        country_code='BR',
        url='https://apiprevmet3.inmet.gov.br/avisos/rss',
        lang='pt-br',
        notes='Official INMET RSS feed whose item links resolve to CAP XML alerts with polygons and warning parameters.',
        provider_v2=True,
    ),
    WarningSource(
        id='nms_belize',
        name='Belize National Meteorological Service CAP Feed (English)',
        backend='nms_belize',
        country_code='BZ',
        url='https://cap-sources.s3.amazonaws.com/bz-nms-en/rss.xml',
        lang='en',
        notes='Official Belize CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteobenin',
        name='METEO-BENIN CAP Feed',
        backend='meteobenin',
        country_code='BJ',
        url='https://www.meteobenin.bj/api/cap/rss.xml',
        lang='fr',
        notes='Official METEO-BENIN CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='dms_botswana',
        name='Botswana Department of Meteorological Services CAP Feed (English)',
        backend='dms_botswana',
        country_code='BW',
        url='https://cap-sources.s3.amazonaws.com/bw-met-en/rss.xml',
        lang='en',
        notes='Official Botswana CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoburkina',
        name='Agence Nationale de la Météorologie du Burkina Faso CAP Feed',
        backend='meteoburkina',
        country_code='BF',
        url='https://meteoburkina.bf/api/cap/rss.xml',
        lang='fr',
        notes='Official Burkina Faso CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='igebu',
        name='Institut Géographique du Burundi CAP Feed',
        backend='igebu',
        country_code='BI',
        url='https://www.igebu.bi/api/cap/rss.xml',
        lang='fr',
        notes='Official Burundi CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteo_cameroon_en',
        name='Cameroon Directorate of National Meteorology CAP Feed (English)',
        backend='meteo_cameroon',
        country_code='CM',
        url='https://cap-sources.s3.amazonaws.com/cm-meteo-en/rss.xml',
        lang='en',
        notes='Official Cameroon CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteo_cameroon_fr',
        name='Cameroon Directorate of National Meteorology CAP Feed (French)',
        backend='meteo_cameroon',
        country_code='CM',
        url='https://cap-sources.s3.amazonaws.com/cm-meteo-fr/rss.xml',
        lang='fr',
        notes='Official Cameroon CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='cma',
        name='China Meteorological Administration CAP Feed',
        backend='swic_mirror',
        country_code='CN',
        url='https://severeweather.wmo.int/v2/cap-alerts/cn-cma-xx/rss.xml',
        lang='en',
        notes='Official CMA public alert feed mirrored through the WMO Severe Weather Information Centre, with linked CAP XML alerts.',
        provider_v2=True,
    ),
    WarningSource(
        id='dmn_car',
        name='Direction de la Météorologie Nationale CAP Feed',
        backend='generic_cap',
        country_code='CF',
        url='https://cap-sources.s3.amazonaws.com/cf-dmn-fr/rss.xml',
        lang='fr',
        notes='Official Central African Republic CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteotchad',
        name='Agence Nationale de la Météorologie du Tchad CAP Feed',
        backend='meteotchad',
        country_code='TD',
        url='https://www.meteotchad.org/api/cap/rss.xml',
        lang='fr',
        notes='Official Chad CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteochile',
        name='Dirección Meteorológica de Chile CAP Feed',
        backend='meteochile',
        country_code='CL',
        url='https://archivos.meteochile.gob.cl/portaldmc/rss/rss.php',
        lang='es',
        notes='Official MeteoChile CAP RSS feed with direct CAP XML links and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteocomores',
        name='Diréction de la Météorologie Nationale des Comores CAP Feed',
        backend='meteocomores',
        country_code='KM',
        url='https://meteocomores.km/api/cap/rss.xml',
        lang='fr',
        notes='Official Comoros CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='dirmet_cg',
        name='Direction de la Météorologie Nationale du Congo CAP Feed',
        backend='dirmet_cg',
        country_code='CG',
        url='https://dirmet.cg/api/cap/rss.xml',
        lang='fr',
        notes='Official Congo CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteordcongo',
        name='Météo RD Congo (METTELSAT) CAP Feed',
        backend='meteordcongo',
        country_code='CD',
        url='https://meteordcongo.cd/api/cap/rss.xml',
        lang='fr',
        notes='Official DR Congo CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='sodexam',
        name="SODEXAM CAP Feed",
        backend='generic_cap',
        country_code='CI',
        url='https://cap-sources.s3.amazonaws.com/ci-sodexam-fr/rss.xml',
        lang='fr',
        notes="Official Côte d'Ivoire CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.",
    ),
    WarningSource(
        id='meteodjibouti',
        name='Agence Nationale de la Météorologie de Djibouti CAP Feed',
        backend='meteodjibouti',
        country_code='DJ',
        url='https://meteodjibouti.dj/api/cap/rss.xml',
        lang='fr',
        notes='Official Djibouti CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='ethiomet',
        name='Ethiopian Meteorology Institute CAP Feed',
        backend='ethiomet',
        country_code='ET',
        url='https://www.ethiomet.gov.et/api/cap/rss.xml',
        lang='en',
        notes='Official Ethiopian Meteorology Institute CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteogambia',
        name='Department of Water Resources, The Gambia CAP Feed',
        backend='meteogambia',
        country_code='GM',
        url='https://meteogambia.gm/api/cap/rss.xml',
        lang='en',
        notes='Official Gambia CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='dgm_gabon',
        name='Direction Generale de la Météorologie CAP Feed',
        backend='generic_cap',
        country_code='GA',
        url='https://cap-sources.s3.amazonaws.com/ga-dgm-fr/rss.xml',
        lang='fr',
        notes='Official Gabon CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='gmet',
        name='Ghana Meteorological Agency CAP Feed',
        backend='gmet',
        country_code='GH',
        url='https://www.meteo.gov.gh/api/cap/rss.xml',
        lang='en',
        notes='Official Ghana CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='anmeteo',
        name='Agence Nationale de la Météorologie CAP Feed',
        backend='anmeteo',
        country_code='GN',
        url='https://anmeteo.gov.gn/api/cap/rss.xml',
        lang='fr',
        notes='Official Guinea CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoguinebissau',
        name='Instituto Nacional de Meteorologia da Guine-Bissau CAP Feed',
        backend='meteoguinebissau',
        country_code='GW',
        url='https://meteoguinebissau.gw/api/cap/rss.xml',
        lang='pt',
        notes='Official Guinea-Bissau CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='hydromet_guyana',
        name='HydroMet Guyana CAP Feed (English)',
        backend='hydromet_guyana',
        country_code='GY',
        url='https://cap-sources.s3.amazonaws.com/gy-hms-en/rss.xml',
        lang='en',
        notes='Official Guyana CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='dmh_py',
        name='Dirección de Meteorología e Hidrología CAP Feed (Spanish)',
        backend='dmh_py',
        country_code='PY',
        url='https://cap-sources.s3.amazonaws.com/py-dmh-es/rss.xml',
        lang='es',
        notes='Official Paraguay CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='qatar_caa_en',
        name='Qatar Civil Aviation Authority CAP Feed (English)',
        backend='qatar_caa',
        country_code='QA',
        url='https://cap-sources.s3.amazonaws.com/qa-caa-en/rss.xml',
        lang='en',
        notes='Official Qatar CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='qatar_caa_ar',
        name='Qatar Civil Aviation Authority CAP Feed (Arabic)',
        backend='qatar_caa',
        country_code='QA',
        url='https://cap-sources.s3.amazonaws.com/qa-caa-ar/rss.xml',
        lang='ar',
        notes='Official Qatar CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='imd_india',
        name='India Meteorological Department CAP Feed (English)',
        backend='imd_india',
        country_code='IN',
        url='https://cap-sources.s3.amazonaws.com/in-imd-en/rss.xml',
        lang='en',
        notes='Official India Meteorological Department CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='met_eireann',
        name='Met Eireann CAP Feed',
        backend='met_eireann',
        country_code='IE',
        url='https://www.met.ie/warningsxml/rss.xml',
        lang='en',
        notes='Official Met Eireann CAP RSS feed with direct CAP XML links, EMMA geocodes, and awareness parameters.',
        provider_v2=True,
    ),
    WarningSource(
        id='jmd_en',
        name='Jordan Meteorological Department CAP Feed (English)',
        backend='jmd',
        country_code='JO',
        url='https://cap-sources.s3.amazonaws.com/jo-meteo-en/rss.xml',
        lang='en',
        notes='Official Jordan CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='jmd_ar',
        name='Jordan Meteorological Department CAP Feed (Arabic)',
        backend='jmd',
        country_code='JO',
        url='https://cap-sources.s3.amazonaws.com/jo-meteo-ar/rss.xml',
        lang='ar',
        notes='Official Jordan CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='msj',
        name='Meteorological Service of Jamaica CAP Feed',
        backend='msj',
        country_code='JM',
        url='https://alert.metservice.gov.jm/capfeed.php',
        lang='en',
        notes='Official Meteorological Service of Jamaica CAP Atom feed with linked CAP XML alerts.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteo_madagascar_en',
        name='Operational Meteorology CAP Feed (English)',
        backend='generic_cap',
        country_code='MG',
        url='https://cap-sources.s3.amazonaws.com/mg-meteo-en/rss.xml',
        lang='en',
        notes='Official Madagascar CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='dmh_myanmar',
        name='Department of Meteorology and Hydrology Myanmar Warnings Feed',
        backend='dmh_myanmar',
        country_code='MM',
        url='https://feeds-dmh.zamg.ac.at/feeds/dmh-warnings',
        lang='en',
        notes='Official DMH Myanmar Atom warnings feed with linked CAP alerts.',
        provider_v2=True,
    ),
    WarningSource(
        id='met_oman_en',
        name='Directorate General of Meteorology CAP Feed (English)',
        backend='generic_cap',
        country_code='OM',
        url='https://cap-sources.s3.amazonaws.com/om-met-en/rss.xml',
        lang='en',
        notes='Official Oman CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='tuvmet',
        name='Tuvalu Meteorological Service CAP Feed',
        backend='generic_cap',
        country_code='TV',
        url='https://cap-sources.s3.amazonaws.com/tv-tuvmet-en/rss.xml',
        lang='en',
        notes='Official Tuvalu CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteo_ke',
        name='Kenya Meteorological Department CAP Feed',
        backend='meteo_ke',
        country_code='KE',
        url='https://meteo.go.ke/api/cap/rss.xml',
        lang='en',
        notes='Official Kenya Meteorological Department CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='kma',
        name='Korea Meteorological Administration CAP Feed (English)',
        backend='kma',
        country_code='KR',
        url='https://www.weather.go.kr/w/rss/cap/warning.do',
        lang='en',
        notes='Official Korea Meteorological Administration CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='kyrgyzhydromet_en',
        name='Kyrgyzhydromet CAP Feed (English)',
        backend='kyrgyzhydromet',
        country_code='KG',
        url='https://meteoalert.meteoinfo.ru/kyrgyzstan/cap-feed/en/atom.xml',
        lang='en',
        notes='Official Kyrgyzhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='kyrgyzhydromet_ru',
        name='Kyrgyzhydromet CAP Feed (Russian)',
        backend='kyrgyzhydromet',
        country_code='KG',
        url='https://meteoalert.meteoinfo.ru/kyrgyzstan/cap-feed/ru/atom.xml',
        lang='ru',
        notes='Official Kyrgyzhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoliberia',
        name='Liberia Meteorological Service CAP Feed',
        backend='meteoliberia',
        country_code='LR',
        url='https://meteoliberia.com/api/cap/rss.xml',
        lang='en',
        notes='Official Liberia Meteorological Service CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='smg',
        name='Macao Meteorological and Geophysical Bureau CAP Feed',
        backend='smg',
        country_code='MO',
        url='https://rss.smg.gov.mo/cap_rss.xml',
        lang='en,zh,pt',
        notes='Official Macao CAP RSS feed with linked multilingual CAP XML alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='metmalawi',
        name='Department of Climate Change and Meteorological Services CAP Feed',
        backend='metmalawi',
        country_code='MW',
        url='https://www.metmalawi.gov.mw/api/cap/rss.xml',
        lang='en',
        notes='Official Malawi CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='mms',
        name='Maldives Meteorological Service CAP Feed',
        backend='mms',
        country_code='MV',
        url='https://cap.meteorology.gov.mv/rss/alerts/',
        lang='en',
        notes='Official Maldives CAP RSS feed with linked CAP XML alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteomauritanie',
        name='Office National de la Météorologie CAP Feed',
        backend='meteomauritanie',
        country_code='MR',
        url='https://meteomauritanie.mr/api/cap/rss.xml',
        lang='fr',
        notes='Official Mauritania CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='namem_en',
        name='National Agency for Meteorology and Environmental Monitoring CAP Feed (English)',
        backend='namem',
        country_code='MN',
        url='https://cap-sources.s3.amazonaws.com/mn-namem-en/rss.xml',
        lang='en',
        notes='Official Mongolia CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='inam_mz',
        name='Instituto Nacional de Meteorologia CAP Feed',
        backend='inam_mz',
        country_code='MZ',
        url='https://cap-sources.s3.amazonaws.com/mz-inam-pt/rss.xml',
        lang='pt',
        notes='Official Mozambique CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='nimet_en',
        name='Nigerian Meteorological Agency CAP Feed (English)',
        backend='nimet',
        country_code='NG',
        url='https://cap-sources.s3.amazonaws.com/ng-nimet-en/rss.xml',
        lang='en',
        notes='Official Nigeria CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='kazhydromet_en',
        name='Kazhydromet CAP Feed (English)',
        backend='kazhydromet',
        country_code='KZ',
        url='https://meteoalert.meteoinfo.ru/kazakhstan/cap-feed/en/atom.xml',
        lang='en',
        notes='Official Kazhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='kazhydromet_ru',
        name='Kazhydromet CAP Feed (Russian)',
        backend='kazhydromet',
        country_code='KZ',
        url='https://meteoalert.meteoinfo.ru/kazakhstan/cap-feed/ru/atom.xml',
        lang='ru',
        notes='Official Kazhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='hydrometcenter_en',
        name='Hydrometcenter of Russia CAP Feed (English)',
        backend='hydrometcenter',
        country_code='RU',
        url='https://meteoinfo.ru/hmc-output/cap/cap-feed/en/atom.xml',
        lang='en',
        notes='Official Hydrometcenter of Russia CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='hydrometcenter_ru',
        name='Hydrometcenter of Russia CAP Feed (Russian)',
        backend='hydrometcenter',
        country_code='RU',
        url='https://meteoinfo.ru/hmc-output/cap/cap-feed/ru/atom.xml',
        lang='ru',
        notes='Official Hydrometcenter of Russia CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='hko',
        name='Hong Kong Observatory CAP Feed',
        backend='hko',
        country_code='HK',
        url='https://alerts.weather.gov.hk/V1/cap_atom.xml',
        lang='en,zh',
        notes='Official Hong Kong Observatory CAP Atom feed with linked CAP XML alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteo_sc',
        name='Seychelles Meteorological Authority CAP Feed',
        backend='meteo_sc',
        country_code='SC',
        url='https://www.meteo.sc/api/cap/rss.xml',
        lang='en',
        notes='Official Seychelles Meteorological Authority CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='slmet',
        name='Sierra Leone Meteorological Agency CAP Feed',
        backend='slmet',
        country_code='SL',
        url='https://slmet.gov.sl/api/cap/rss.xml',
        lang='en',
        notes='Official Sierra Leone Meteorological Agency CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='solomon_met',
        name='Solomon Islands Meteorological Service CAP Feed (English)',
        backend='solomon_met',
        country_code='SB',
        url='https://cap-sources.s3.amazonaws.com/sb-met-en/rss.xml',
        lang='en',
        notes='Official Solomon Islands CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteosouthsudan',
        name='South Sudan Meteorological Services CAP Feed',
        backend='meteosouthsudan',
        country_code='SS',
        url='https://meteosouthsudan.com.ss/api/cap/rss.xml',
        lang='en',
        notes='Official South Sudan Meteorological Services CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='aemet',
        name='AEMET CAP Feed',
        backend='aemet',
        country_code='ES',
        url='https://www.aemet.es/documentos_d/eltiempo/prediccion/avisos/rss/CAP_AFAE_wah_RSS.xml',
        lang='es,en',
        notes='Official AEMET CAP RSS feed with linked CAP XML, bilingual CAP info blocks, and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteosudan',
        name='Sudan Meteorological Authority CAP Feed',
        backend='meteosudan',
        country_code='SD',
        url='https://meteosudan.sd/api/cap/rss.xml',
        lang='ar',
        notes='Official Sudan Meteorological Authority CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteotogo',
        name='METEO TOGO (ANAMET) CAP Feed',
        backend='meteotogo',
        country_code='TG',
        url='https://meteotogo.tg/api/cap/rss.xml',
        lang='fr',
        notes='Official METEO TOGO (ANAMET) CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='anacim',
        name="Agence Nationale de l'Aviation Civile et de la Météorologie CAP Feed",
        backend='generic_cap',
        country_code='SN',
        url='https://cap-sources.s3.amazonaws.com/sn-anacim-fr/rss.xml',
        lang='fr',
        notes='Official Senegal CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='inmeteo_stp',
        name='Instituto Nacional de Meteorologia CAP Feed',
        backend='generic_cap',
        country_code='ST',
        url='https://cap-sources.s3.amazonaws.com/st-meteo-pt/rss.xml',
        lang='pt',
        notes='Official São Tomé and Príncipe CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='inm_tunisia_en',
        name='National Institute of Meteorology CAP Feed (English)',
        backend='generic_cap',
        country_code='TN',
        url='https://cap-sources.s3.amazonaws.com/tn-meteo-en/rss.xml',
        lang='en',
        notes='Official Tunisia CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='ttms',
        name='Trinidad and Tobago Meteorological Service CAP Feed',
        backend='ttms',
        country_code='TT',
        url='https://metproducts.gov.tt/ttms/public/api/feed?type=rss',
        lang='en',
        notes='Official Trinidad and Tobago Meteorological Service CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='tci_en',
        name='TCI Emergency Alerts CAP Feed (English)',
        backend='tci',
        country_code='TC',
        url='https://cap-sources.s3.amazonaws.com/tc-gov-en/rss.xml',
        lang='en',
        notes='Official Turks and Caicos Islands CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and mixed polygon/circle geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='tci_ht',
        name='TCI Emergency Alerts CAP Feed (Haitian Creole)',
        backend='tci',
        country_code='TC',
        url='https://cap-sources.s3.amazonaws.com/tc-gov-ht/rss.xml',
        lang='ht',
        notes='Official Turks and Caicos Islands CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and mixed polygon/circle geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='tci_es',
        name='TCI Emergency Alerts CAP Feed (Spanish)',
        backend='tci',
        country_code='TC',
        url='https://cap-sources.s3.amazonaws.com/tc-gov-es/rss.xml',
        lang='es',
        notes='Official Turks and Caicos Islands CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and mixed polygon/circle geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='svg_met',
        name='Saint Vincent and the Grenadines Meteorological Services CAP Feed',
        backend='capews',
        country_code='VC',
        url='https://vct-primary.capews.com/capews/public/atom?type=cap',
        lang='en',
        notes='Official CAPEWS Atom feed for Saint Vincent and the Grenadines with linked CAP alerts.',
        provider_v2=True,
    ),
    WarningSource(
        id='tmd_en',
        name='Thai Meteorological Department CAP Feed (English)',
        backend='tmd',
        country_code='TH',
        url='https://www.tmd.go.th/en/api/xml/CAP',
        lang='en',
        notes='Official Thai Meteorological Department CAP RSS feed with linked CAP XML alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='tmd_th',
        name='Thai Meteorological Department CAP Feed (Thai)',
        backend='tmd',
        country_code='TH',
        url='https://www.tmd.go.th/api/xml/CAP',
        lang='th',
        notes='Official Thai Meteorological Department CAP RSS feed with linked CAP XML alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='tma_en',
        name='Tanzania Meteorological Authority CAP Feed (English)',
        backend='tma',
        country_code='TZ',
        url='https://cap-sources.s3.amazonaws.com/tz-tma-en/rss.xml',
        lang='en',
        notes='Official Tanzania Meteorological Authority CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='tma_sw',
        name='Tanzania Meteorological Authority CAP Feed (Swahili)',
        backend='tma',
        country_code='TZ',
        url='https://cap-sources.s3.amazonaws.com/tz-tma-sw/rss.xml',
        lang='sw',
        notes='Official Tanzania Meteorological Authority CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='inumet',
        name='Instituto Uruguayo de Meteorología CAP Feed',
        backend='inumet',
        country_code='UY',
        url='https://www.inumet.gub.uy/reportes/riesgo/rss.xml',
        lang='es',
        notes='Official INUMET CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='uzhydromet_en',
        name='Uzhydromet CAP Feed (English)',
        backend='uzhydromet',
        country_code='UZ',
        url='https://meteoalert.meteoinfo.ru/uzbekistan/cap-feed/en/atom.xml',
        lang='en',
        notes='Official Uzhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='uzhydromet_ru',
        name='Uzhydromet CAP Feed (Russian)',
        backend='uzhydromet',
        country_code='UZ',
        url='https://meteoalert.meteoinfo.ru/uzbekistan/cap-feed/ru/atom.xml',
        lang='ru',
        notes='Official Uzhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='vmgd',
        name='Vanuatu Meteorology and Geo-Hazards Department CAP Feed',
        backend='vmgd',
        country_code='VU',
        url='https://cap-sources.s3.amazonaws.com/vu-vmgd-en/rss.xml',
        lang='en',
        notes='Official Vanuatu Meteorology and Geo-Hazards Department CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='zmd',
        name='Zambia Meteorological Department CAP Feed',
        backend='zmd',
        country_code='ZM',
        url='https://zmd.gov.zm/api/cap/rss.xml',
        lang='en',
        notes='Official Zambia Meteorological Department CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='weatherzw',
        name='Meteorological Services Department of Zimbabwe CAP Feed',
        backend='weatherzw',
        country_code='ZW',
        url='https://www.weatherzw.org.zw/api/cap/rss.xml',
        lang='en',
        notes='Official Meteorological Services Department of Zimbabwe CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='saint_lucia',
        name='Saint Lucia Meteorological Service CAP Feed',
        backend='saint_lucia',
        country_code='LC',
        url='https://saint-lucia.cap-composer.wiscaribbeancmo.org/api/cap/rss.xml',
        lang='en',
        notes='Official Saint Lucia CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='indomet',
        name='Instituto Dominicano de Meteorología CAP Feed (Spanish)',
        backend='indomet',
        country_code='DO',
        url='https://cap-sources.s3.amazonaws.com/do-indomet-es/rss.xml',
        lang='es',
        notes='Official Dominican Republic CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='inamhi',
        name='Instituto Nacional de Meteorología e Hidrología CAP Feed (Spanish)',
        backend='inamhi',
        country_code='EC',
        url='https://cap-sources.s3.amazonaws.com/ec-inamhi-es/rss.xml',
        lang='es',
        notes='Official Ecuador CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='eswatini_met',
        name='Eswatini Meteorological Service CAP Feed (English)',
        backend='eswatini_met',
        country_code='SZ',
        url='https://cap-sources.s3.amazonaws.com/sz-met-en/rss.xml',
        lang='en',
        notes='Official Eswatini CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteo_cw_en',
        name='Meteorological Department Curaçao CAP Feed (English)',
        backend='meteo_cw',
        country_code='CW',
        url='https://www.meteo.cw/rss/CAP_en.xml',
        lang='en',
        notes='Official Curaçao CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteo_cw_nl',
        name='Meteorological Department Curaçao CAP Feed (Dutch)',
        backend='meteo_cw',
        country_code='CW',
        url='https://www.meteo.cw/rss/CAP_nl.xml',
        lang='nl',
        notes='Official Curaçao CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteo_cw_pap',
        name='Meteorological Department Curaçao CAP Feed (Papiamento)',
        backend='meteo_cw',
        country_code='CW',
        url='https://www.meteo.cw/rss/CAP_pap.xml',
        lang='pap',
        notes='Official Curaçao CAP RSS feed with linked CAP XML and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='metservice_nz',
        name='MetService New Zealand CAP Feed',
        backend='metservice_nz',
        country_code='NZ',
        url='https://alerts.metservice.com/cap/rss',
        lang='en',
        notes='Official MetService public CAP alert RSS feed.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteo_suriname_en',
        name='Suriname Meteorological Service CAP Feed (English)',
        backend='generic_cap',
        country_code='SR',
        url='https://cap-sources.s3.amazonaws.com/sr-meteo-en/rss.xml',
        lang='en',
        notes='Official Suriname CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='mms_mauritius',
        name='Mauritius Meteorological Services CAP Feed',
        backend='generic_cap',
        country_code='MU',
        url='https://cap-sources.s3.amazonaws.com/mu-mms-en/rss.xml',
        lang='en',
        notes='Official Mauritius CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='dnmg_timor_en',
        name='National Directorate of Meteorology and Geophysics CAP Feed (English)',
        backend='generic_cap',
        country_code='TL',
        url='https://cap-sources.s3.amazonaws.com/tl-dnmg-en/rss.xml',
        lang='en',
        notes='Official Timor-Leste CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='smn_mexico',
        name='Servicio Meteorológico Nacional de México CAP Feed',
        backend='smn_mexico',
        country_code='MX',
        url='https://smn.conagua.gob.mx/tools/PHP/feedsmn/cap.php',
        lang='es',
        notes='Official SMN Mexico CAP Atom feed with direct CAP XML links and warning parameters.',
        provider_v2=True,
    ),
    WarningSource(
        id='imhpa',
        name='IMHPA CAP Feed',
        backend='generic_cap',
        country_code='PA',
        url='https://cap-sources.s3.amazonaws.com/pa-imhpa-es/rss.xml',
        lang='es',
        notes='Official Panama CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='pagasa',
        name='PAGASA Alert Feed',
        backend='pagasa',
        country_code='PH',
        url='https://publicalert.pagasa.dost.gov.ph/feeds/',
        lang='en',
        notes='Official PAGASA Atom alert feed with linked CAP alerts.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_andorra',
        name='Meteoalarm Atom Feed (Andorra)',
        backend='meteoalarm_atom',
        country_code='AD',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-andorra',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_austria',
        name='Meteoalarm Atom Feed (Austria)',
        backend='meteoalarm_atom',
        country_code='AT',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-austria',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_belgium',
        name='Meteoalarm Atom Feed (Belgium)',
        backend='meteoalarm_atom',
        country_code='BE',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-belgium',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_bosnia_herzegovina',
        name='Meteoalarm Atom Feed (Bosnia and Herzegovina)',
        backend='meteoalarm_atom',
        country_code='BA',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-bosnia-herzegovina',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_bulgaria',
        name='Meteoalarm Atom Feed (Bulgaria)',
        backend='meteoalarm_atom',
        country_code='BG',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-bulgaria',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_croatia',
        name='Meteoalarm Atom Feed (Croatia)',
        backend='meteoalarm_atom',
        country_code='HR',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-croatia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_cyprus',
        name='Meteoalarm Atom Feed (Cyprus)',
        backend='meteoalarm_atom',
        country_code='CY',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-cyprus',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_czechia',
        name='Meteoalarm Atom Feed (Czechia)',
        backend='meteoalarm_atom',
        country_code='CZ',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-czechia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_denmark',
        name='Meteoalarm Atom Feed (Denmark)',
        backend='meteoalarm_atom',
        country_code='DK',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-denmark',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_estonia',
        name='Meteoalarm Atom Feed (Estonia)',
        backend='meteoalarm_atom',
        country_code='EE',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-estonia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_france',
        name='Meteoalarm Atom Feed (France)',
        backend='meteoalarm_atom',
        country_code='FR',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-france',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_greece',
        name='Meteoalarm Atom Feed (Greece)',
        backend='meteoalarm_atom',
        country_code='GR',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-greece',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_hungary',
        name='Meteoalarm Atom Feed (Hungary)',
        backend='meteoalarm_atom',
        country_code='HU',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-hungary',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_israel',
        name='Meteoalarm Atom Feed (Israel)',
        backend='meteoalarm_atom',
        country_code='IL',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-israel',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_italy',
        name='Meteoalarm Atom Feed (Italy)',
        backend='meteoalarm_atom',
        country_code='IT',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-italy',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_latvia',
        name='Meteoalarm Atom Feed (Latvia)',
        backend='meteoalarm_atom',
        country_code='LV',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-latvia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_lithuania',
        name='Meteoalarm Atom Feed (Lithuania)',
        backend='meteoalarm_atom',
        country_code='LT',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-lithuania',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_luxembourg',
        name='Meteoalarm Atom Feed (Luxembourg)',
        backend='meteoalarm_atom',
        country_code='LU',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-luxembourg',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_malta',
        name='Meteoalarm Atom Feed (Malta)',
        backend='meteoalarm_atom',
        country_code='MT',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-malta',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_montenegro',
        name='Meteoalarm Atom Feed (Montenegro)',
        backend='meteoalarm_atom',
        country_code='ME',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-montenegro',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_netherlands',
        name='Meteoalarm Atom Feed (Netherlands)',
        backend='meteoalarm_atom',
        country_code='NL',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-netherlands',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_north_macedonia',
        name='Meteoalarm Atom Feed (North Macedonia)',
        backend='meteoalarm_atom',
        country_code='MK',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-republic-of-north-macedonia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_poland',
        name='Meteoalarm Atom Feed (Poland)',
        backend='meteoalarm_atom',
        country_code='PL',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-poland',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_portugal',
        name='Meteoalarm Atom Feed (Portugal)',
        backend='meteoalarm_atom',
        country_code='PT',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-portugal',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_moldova',
        name='Meteoalarm Atom Feed (Republic of Moldova)',
        backend='meteoalarm_atom',
        country_code='MD',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-moldova',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_romania',
        name='Meteoalarm Atom Feed (Romania)',
        backend='meteoalarm_atom',
        country_code='RO',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-romania',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_serbia',
        name='Meteoalarm Atom Feed (Serbia)',
        backend='meteoalarm_atom',
        country_code='RS',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-serbia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_slovakia',
        name='Meteoalarm Atom Feed (Slovakia)',
        backend='meteoalarm_atom',
        country_code='SK',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-slovakia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_slovenia',
        name='Meteoalarm Atom Feed (Slovenia)',
        backend='meteoalarm_atom',
        country_code='SI',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-slovenia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_sweden',
        name='Meteoalarm Atom Feed (Sweden)',
        backend='meteoalarm_atom',
        country_code='SE',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-sweden',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_switzerland',
        name='Meteoalarm Atom Feed (Switzerland)',
        backend='meteoalarm_atom',
        country_code='CH',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-switzerland',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and verified polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_united_kingdom',
        name='Meteoalarm Atom Feed (United Kingdom)',
        backend='meteoalarm_atom',
        country_code='GB',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-united-kingdom',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
        provider_v2=True,
    ),
    WarningSource(
        id='meteoalarm_atom_ukraine',
        name='Meteoalarm Atom Feed (Ukraine)',
        backend='meteoalarm_atom',
        country_code='UA',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-ukraine',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and verified MultiPolygon geometry.',
        provider_v2=True,
    ),
)

SOURCE_BY_ID = {source.id: source for source in SOURCES}
