"""Static source definitions for official warning feeds."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class WarningSource:
    """Definition of one official warning source."""

    id: str
    name: str
    backend: str
    country_code: str | None
    url: str | None
    lang: str | None = None
    notes: str | None = None


SOURCES: tuple[WarningSource, ...] = (
    WarningSource(
        id='nws',
        name='U.S. National Weather Service',
        backend='nws',
        country_code='US',
        url='https://api.weather.gov/alerts/active',
        lang='en',
        notes='Official NWS alerts API with native point queries.',
    ),
    WarningSource(
        id='geomet',
        name='Environment Canada GeoMet',
        backend='geomet',
        country_code='CA',
        url='https://api.weather.gc.ca/collections/weather-alerts/items',
        lang='en,fr',
        notes='Official GeoMet OGC API weather-alerts collection.',
    ),
    WarningSource(
        id='dwd_cap_en',
        name='Deutscher Wetterdienst CAP Feed (English)',
        backend='generic_cap',
        country_code='DE',
        url='https://www.dwd.de/DWD/warnungen/cap-feed/en/rss.xml',
        lang='en',
        notes='Official DWD CAP RSS feed with linked CAP 1.2 alerts.',
    ),
    WarningSource(
        id='dwd_cap_de',
        name='Deutscher Wetterdienst CAP Feed (German)',
        backend='generic_cap',
        country_code='DE',
        url='https://www.dwd.de/DWD/warnungen/cap-feed/de/rss.xml',
        lang='de',
        notes='Official DWD CAP RSS feed; catalogued separately from the English feed.',
    ),
    WarningSource(
        id='fmi_cap_en',
        name='Finnish Meteorological Institute CAP Feed (English)',
        backend='generic_cap',
        country_code='FI',
        url='https://alerts.fmi.fi/cap/feed/rss_en-GB.rss',
        lang='en',
        notes='Official FMI CAP RSS feed with linked multilingual CAP alerts.',
    ),
    WarningSource(
        id='fmi_cap_fi',
        name='Finnish Meteorological Institute CAP Feed (Finnish)',
        backend='generic_cap',
        country_code='FI',
        url='https://alerts.fmi.fi/cap/feed/rss_fi-FI.rss',
        lang='fi',
        notes='Official FMI CAP RSS feed with linked multilingual CAP alerts.',
    ),
    WarningSource(
        id='fmi_cap_sv',
        name='Finnish Meteorological Institute CAP Feed (Swedish)',
        backend='generic_cap',
        country_code='FI',
        url='https://alerts.fmi.fi/cap/feed/rss_sv-FI.rss',
        lang='sv',
        notes='Official FMI CAP RSS feed with linked multilingual CAP alerts.',
    ),
    WarningSource(
        id='met_no_cap',
        name='MET Norway MetAlerts CAP Feed',
        backend='generic_cap',
        country_code='NO',
        url='https://alert.met.no/alerts',
        lang='en,no',
        notes='Official MET Norway warning feed with linked bilingual CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='nve_cap',
        name='NVE CAP Feed',
        backend='generic_cap',
        country_code='NO',
        url='https://cap.nve.no/',
        lang='en,no',
        notes='Official Norwegian Water Resources and Energy Directorate CAP feed with linked bilingual CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='vedur_cap',
        name='Icelandic Meteorological Office CAP Feed',
        backend='generic_cap',
        country_code='IS',
        url='https://api.vedur.is/cap/v1/capbroker/active/feed/met',
        lang='en,is',
        notes='Official IMO CAP RSS feed with linked bilingual CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='bmkg_cap_en',
        name='BMKG Nowcast CAP Feed (English)',
        backend='generic_cap',
        country_code='ID',
        url='https://www.bmkg.go.id/alerts/nowcast/en',
        lang='en',
        notes='Official BMKG CAP RSS feed; downstream applications must credit BMKG as the data source.',
    ),
    WarningSource(
        id='bmkg_cap_id',
        name='BMKG Nowcast CAP Feed (Indonesian)',
        backend='generic_cap',
        country_code='ID',
        url='https://www.bmkg.go.id/alerts/nowcast/id',
        lang='id',
        notes='Official BMKG CAP RSS feed; downstream applications must credit BMKG as the data source.',
    ),
    WarningSource(
        id='smn_cap',
        name='Servicio Meteorológico Nacional CAP Feed',
        backend='generic_cap',
        country_code='AR',
        url='https://ssl.smn.gob.ar/CAP/AR.php',
        lang='es',
        notes='Official SMN Argentina CAP RSS feed with direct CAP alert links and polygon geometry.',
    ),
    WarningSource(
        id='bh_meteo_en',
        name='Bahrain Meteorological Directorate CAP Feed (English)',
        backend='generic_cap',
        country_code='BH',
        url='https://cap-sources.s3.amazonaws.com/bh-meteo-en/rss.xml',
        lang='en',
        notes='Official Bahrain CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='bh_meteo_ar',
        name='Bahrain Meteorological Directorate CAP Feed (Arabic)',
        backend='generic_cap',
        country_code='BH',
        url='https://cap-sources.s3.amazonaws.com/bh-meteo-ar/rss.xml',
        lang='ar',
        notes='Official Bahrain CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='bz_nms_en',
        name='Belize National Meteorological Service CAP Feed (English)',
        backend='generic_cap',
        country_code='BZ',
        url='https://cap-sources.s3.amazonaws.com/bz-nms-en/rss.xml',
        lang='en',
        notes='Official Belize CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteobenin_cap',
        name='METEO-BENIN CAP Feed',
        backend='generic_cap',
        country_code='BJ',
        url='https://www.meteobenin.bj/api/cap/rss.xml',
        lang='fr',
        notes='Official METEO-BENIN CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='bw_met_en',
        name='Botswana Department of Meteorological Services CAP Feed (English)',
        backend='generic_cap',
        country_code='BW',
        url='https://cap-sources.s3.amazonaws.com/bw-met-en/rss.xml',
        lang='en',
        notes='Official Botswana CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteoburkina_cap',
        name='Agence Nationale de la Météorologie du Burkina Faso CAP Feed',
        backend='generic_cap',
        country_code='BF',
        url='https://meteoburkina.bf/api/cap/rss.xml',
        lang='fr',
        notes='Official Burkina Faso CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='igebu_cap',
        name='Institut Géographique du Burundi CAP Feed',
        backend='generic_cap',
        country_code='BI',
        url='https://www.igebu.bi/api/cap/rss.xml',
        lang='fr',
        notes='Official Burundi CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='cm_meteo_en',
        name='Cameroon Directorate of National Meteorology CAP Feed (English)',
        backend='generic_cap',
        country_code='CM',
        url='https://cap-sources.s3.amazonaws.com/cm-meteo-en/rss.xml',
        lang='en',
        notes='Official Cameroon CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='cm_meteo_fr',
        name='Cameroon Directorate of National Meteorology CAP Feed (French)',
        backend='generic_cap',
        country_code='CM',
        url='https://cap-sources.s3.amazonaws.com/cm-meteo-fr/rss.xml',
        lang='fr',
        notes='Official Cameroon CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteotchad_cap',
        name='Agence Nationale de la Météorologie du Tchad CAP Feed',
        backend='generic_cap',
        country_code='TD',
        url='https://www.meteotchad.org/api/cap/rss.xml',
        lang='fr',
        notes='Official Chad CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteochile_cap',
        name='Dirección Meteorológica de Chile CAP Feed',
        backend='generic_cap',
        country_code='CL',
        url='https://archivos.meteochile.gob.cl/portaldmc/rss/rss.php',
        lang='es',
        notes='Official MeteoChile CAP RSS feed with direct CAP XML links and polygon geometry.',
    ),
    WarningSource(
        id='meteocomores_cap',
        name='Diréction de la Météorologie Nationale des Comores CAP Feed',
        backend='generic_cap',
        country_code='KM',
        url='https://meteocomores.km/api/cap/rss.xml',
        lang='fr',
        notes='Official Comoros CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='dirmet_cg_cap',
        name='Direction de la Météorologie Nationale du Congo CAP Feed',
        backend='generic_cap',
        country_code='CG',
        url='https://dirmet.cg/api/cap/rss.xml',
        lang='fr',
        notes='Official Congo CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteordcongo_cap',
        name='Météo RD Congo (METTELSAT) CAP Feed',
        backend='generic_cap',
        country_code='CD',
        url='https://meteordcongo.cd/api/cap/rss.xml',
        lang='fr',
        notes='Official DR Congo CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteodjibouti_cap',
        name='Agence Nationale de la Météorologie de Djibouti CAP Feed',
        backend='generic_cap',
        country_code='DJ',
        url='https://meteodjibouti.dj/api/cap/rss.xml',
        lang='fr',
        notes='Official Djibouti CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='ethiomet_cap',
        name='Ethiopian Meteorology Institute CAP Feed',
        backend='generic_cap',
        country_code='ET',
        url='https://www.ethiomet.gov.et/api/cap/rss.xml',
        lang='en',
        notes='Official Ethiopian Meteorology Institute CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteogambia_cap',
        name='Department of Water Resources, The Gambia CAP Feed',
        backend='generic_cap',
        country_code='GM',
        url='https://meteogambia.gm/api/cap/rss.xml',
        lang='en',
        notes='Official Gambia CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='gmet_cap',
        name='Ghana Meteorological Agency CAP Feed',
        backend='generic_cap',
        country_code='GH',
        url='https://www.meteo.gov.gh/api/cap/rss.xml',
        lang='en',
        notes='Official Ghana CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='anmeteo_cap',
        name='Agence Nationale de la Météorologie CAP Feed',
        backend='generic_cap',
        country_code='GN',
        url='https://anmeteo.gov.gn/api/cap/rss.xml',
        lang='fr',
        notes='Official Guinea CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteoguinebissau_cap',
        name='Instituto Nacional de Meteorologia da Guine-Bissau CAP Feed',
        backend='generic_cap',
        country_code='GW',
        url='https://meteoguinebissau.gw/api/cap/rss.xml',
        lang='pt',
        notes='Official Guinea-Bissau CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='gy_hms_en',
        name='HydroMet Guyana CAP Feed (English)',
        backend='generic_cap',
        country_code='GY',
        url='https://cap-sources.s3.amazonaws.com/gy-hms-en/rss.xml',
        lang='en',
        notes='Official Guyana CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='py_dmh_es',
        name='Dirección de Meteorología e Hidrología CAP Feed (Spanish)',
        backend='generic_cap',
        country_code='PY',
        url='https://cap-sources.s3.amazonaws.com/py-dmh-es/rss.xml',
        lang='es',
        notes='Official Paraguay CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='qa_caa_en',
        name='Qatar Civil Aviation Authority CAP Feed (English)',
        backend='generic_cap',
        country_code='QA',
        url='https://cap-sources.s3.amazonaws.com/qa-caa-en/rss.xml',
        lang='en',
        notes='Official Qatar CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='qa_caa_ar',
        name='Qatar Civil Aviation Authority CAP Feed (Arabic)',
        backend='generic_cap',
        country_code='QA',
        url='https://cap-sources.s3.amazonaws.com/qa-caa-ar/rss.xml',
        lang='ar',
        notes='Official Qatar CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='in_imd_en',
        name='India Meteorological Department CAP Feed (English)',
        backend='generic_cap',
        country_code='IN',
        url='https://cap-sources.s3.amazonaws.com/in-imd-en/rss.xml',
        lang='en',
        notes='Official India Meteorological Department CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='jo_meteo_en',
        name='Jordan Meteorological Department CAP Feed (English)',
        backend='generic_cap',
        country_code='JO',
        url='https://cap-sources.s3.amazonaws.com/jo-meteo-en/rss.xml',
        lang='en',
        notes='Official Jordan CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='jo_meteo_ar',
        name='Jordan Meteorological Department CAP Feed (Arabic)',
        backend='generic_cap',
        country_code='JO',
        url='https://cap-sources.s3.amazonaws.com/jo-meteo-ar/rss.xml',
        lang='ar',
        notes='Official Jordan CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteo_ke_cap',
        name='Kenya Meteorological Department CAP Feed',
        backend='generic_cap',
        country_code='KE',
        url='https://meteo.go.ke/api/cap/rss.xml',
        lang='en',
        notes='Official Kenya Meteorological Department CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='kma_cap_en',
        name='Korea Meteorological Administration CAP Feed (English)',
        backend='generic_cap',
        country_code='KR',
        url='https://www.weather.go.kr/w/rss/cap/warning.do',
        lang='en',
        notes='Official Korea Meteorological Administration CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='kyrgyzhydromet_cap_en',
        name='Kyrgyzhydromet CAP Feed (English)',
        backend='generic_cap',
        country_code='KG',
        url='https://meteoalert.meteoinfo.ru/kyrgyzstan/cap-feed/en/atom.xml',
        lang='en',
        notes='Official Kyrgyzhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='kyrgyzhydromet_cap_ru',
        name='Kyrgyzhydromet CAP Feed (Russian)',
        backend='generic_cap',
        country_code='KG',
        url='https://meteoalert.meteoinfo.ru/kyrgyzstan/cap-feed/ru/atom.xml',
        lang='ru',
        notes='Official Kyrgyzhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteoliberia_cap',
        name='Liberia Meteorological Service CAP Feed',
        backend='generic_cap',
        country_code='LR',
        url='https://meteoliberia.com/api/cap/rss.xml',
        lang='en',
        notes='Official Liberia Meteorological Service CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='smg_cap',
        name='Macao Meteorological and Geophysical Bureau CAP Feed',
        backend='generic_cap',
        country_code='MO',
        url='https://rss.smg.gov.mo/cap_rss.xml',
        lang='en,zh,pt',
        notes='Official Macao CAP RSS feed with linked multilingual CAP XML alerts and polygon geometry.',
    ),
    WarningSource(
        id='metmalawi_cap',
        name='Department of Climate Change and Meteorological Services CAP Feed',
        backend='generic_cap',
        country_code='MW',
        url='https://www.metmalawi.gov.mw/api/cap/rss.xml',
        lang='en',
        notes='Official Malawi CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='mms_cap',
        name='Maldives Meteorological Service CAP Feed',
        backend='generic_cap',
        country_code='MV',
        url='https://cap.meteorology.gov.mv/rss/alerts/',
        lang='en',
        notes='Official Maldives CAP RSS feed with linked CAP XML alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteomauritanie_cap',
        name='Office National de la Météorologie CAP Feed',
        backend='generic_cap',
        country_code='MR',
        url='https://meteomauritanie.mr/api/cap/rss.xml',
        lang='fr',
        notes='Official Mauritania CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='namem_cap_en',
        name='National Agency for Meteorology and Environmental Monitoring CAP Feed (English)',
        backend='generic_cap',
        country_code='MN',
        url='https://cap-sources.s3.amazonaws.com/mn-namem-en/rss.xml',
        lang='en',
        notes='Official Mongolia CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='inam_mz_cap',
        name='Instituto Nacional de Meteorologia CAP Feed',
        backend='generic_cap',
        country_code='MZ',
        url='https://cap-sources.s3.amazonaws.com/mz-inam-pt/rss.xml',
        lang='pt',
        notes='Official Mozambique CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='nimet_cap_en',
        name='Nigerian Meteorological Agency CAP Feed (English)',
        backend='generic_cap',
        country_code='NG',
        url='https://cap-sources.s3.amazonaws.com/ng-nimet-en/rss.xml',
        lang='en',
        notes='Official Nigeria CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='kazhydromet_cap_en',
        name='Kazhydromet CAP Feed (English)',
        backend='generic_cap',
        country_code='KZ',
        url='https://meteoalert.meteoinfo.ru/kazakhstan/cap-feed/en/atom.xml',
        lang='en',
        notes='Official Kazhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='kazhydromet_cap_ru',
        name='Kazhydromet CAP Feed (Russian)',
        backend='generic_cap',
        country_code='KZ',
        url='https://meteoalert.meteoinfo.ru/kazakhstan/cap-feed/ru/atom.xml',
        lang='ru',
        notes='Official Kazhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='hydrometcenter_ru_cap_en',
        name='Hydrometcenter of Russia CAP Feed (English)',
        backend='generic_cap',
        country_code='RU',
        url='https://meteoinfo.ru/hmc-output/cap/cap-feed/en/atom.xml',
        lang='en',
        notes='Official Hydrometcenter of Russia CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='hydrometcenter_ru_cap_ru',
        name='Hydrometcenter of Russia CAP Feed (Russian)',
        backend='generic_cap',
        country_code='RU',
        url='https://meteoinfo.ru/hmc-output/cap/cap-feed/ru/atom.xml',
        lang='ru',
        notes='Official Hydrometcenter of Russia CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteo_sc_cap',
        name='Seychelles Meteorological Authority CAP Feed',
        backend='generic_cap',
        country_code='SC',
        url='https://www.meteo.sc/api/cap/rss.xml',
        lang='en',
        notes='Official Seychelles Meteorological Authority CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='slmet_cap',
        name='Sierra Leone Meteorological Agency CAP Feed',
        backend='generic_cap',
        country_code='SL',
        url='https://slmet.gov.sl/api/cap/rss.xml',
        lang='en',
        notes='Official Sierra Leone Meteorological Agency CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='sb_met_en',
        name='Solomon Islands Meteorological Service CAP Feed (English)',
        backend='generic_cap',
        country_code='SB',
        url='https://cap-sources.s3.amazonaws.com/sb-met-en/rss.xml',
        lang='en',
        notes='Official Solomon Islands CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteosouthsudan_cap',
        name='South Sudan Meteorological Services CAP Feed',
        backend='generic_cap',
        country_code='SS',
        url='https://meteosouthsudan.com.ss/api/cap/rss.xml',
        lang='en',
        notes='Official South Sudan Meteorological Services CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='aemet_cap',
        name='AEMET CAP Feed',
        backend='generic_cap',
        country_code='ES',
        url='https://www.aemet.es/documentos_d/eltiempo/prediccion/avisos/rss/CAP_AFAE_wah_RSS.xml',
        lang='es,en',
        notes='Official AEMET CAP RSS feed with linked CAP XML, bilingual CAP info blocks, and polygon geometry.',
    ),
    WarningSource(
        id='meteosudan_cap',
        name='Sudan Meteorological Authority CAP Feed',
        backend='generic_cap',
        country_code='SD',
        url='https://meteosudan.sd/api/cap/rss.xml',
        lang='ar',
        notes='Official Sudan Meteorological Authority CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='meteotogo_cap',
        name='METEO TOGO (ANAMET) CAP Feed',
        backend='generic_cap',
        country_code='TG',
        url='https://meteotogo.tg/api/cap/rss.xml',
        lang='fr',
        notes='Official METEO TOGO (ANAMET) CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='ttms_cap',
        name='Trinidad and Tobago Meteorological Service CAP Feed',
        backend='generic_cap',
        country_code='TT',
        url='https://metproducts.gov.tt/ttms/public/api/feed?type=rss',
        lang='en',
        notes='Official Trinidad and Tobago Meteorological Service CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='tc_gov_en',
        name='TCI Emergency Alerts CAP Feed (English)',
        backend='generic_cap',
        country_code='TC',
        url='https://cap-sources.s3.amazonaws.com/tc-gov-en/rss.xml',
        lang='en',
        notes='Official Turks and Caicos Islands CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and mixed polygon/circle geometry.',
    ),
    WarningSource(
        id='tc_gov_ht',
        name='TCI Emergency Alerts CAP Feed (Haitian Creole)',
        backend='generic_cap',
        country_code='TC',
        url='https://cap-sources.s3.amazonaws.com/tc-gov-ht/rss.xml',
        lang='ht',
        notes='Official Turks and Caicos Islands CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and mixed polygon/circle geometry.',
    ),
    WarningSource(
        id='tc_gov_es',
        name='TCI Emergency Alerts CAP Feed (Spanish)',
        backend='generic_cap',
        country_code='TC',
        url='https://cap-sources.s3.amazonaws.com/tc-gov-es/rss.xml',
        lang='es',
        notes='Official Turks and Caicos Islands CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and mixed polygon/circle geometry.',
    ),
    WarningSource(
        id='tz_tma_en',
        name='Tanzania Meteorological Authority CAP Feed (English)',
        backend='generic_cap',
        country_code='TZ',
        url='https://cap-sources.s3.amazonaws.com/tz-tma-en/rss.xml',
        lang='en',
        notes='Official Tanzania Meteorological Authority CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='tz_tma_sw',
        name='Tanzania Meteorological Authority CAP Feed (Swahili)',
        backend='generic_cap',
        country_code='TZ',
        url='https://cap-sources.s3.amazonaws.com/tz-tma-sw/rss.xml',
        lang='sw',
        notes='Official Tanzania Meteorological Authority CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='inumet_cap',
        name='Instituto Uruguayo de Meteorología CAP Feed',
        backend='generic_cap',
        country_code='UY',
        url='https://www.inumet.gub.uy/reportes/riesgo/rss.xml',
        lang='es',
        notes='Official INUMET CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='uzhydromet_cap_en',
        name='Uzhydromet CAP Feed (English)',
        backend='generic_cap',
        country_code='UZ',
        url='https://meteoalert.meteoinfo.ru/uzbekistan/cap-feed/en/atom.xml',
        lang='en',
        notes='Official Uzhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='uzhydromet_cap_ru',
        name='Uzhydromet CAP Feed (Russian)',
        backend='generic_cap',
        country_code='UZ',
        url='https://meteoalert.meteoinfo.ru/uzbekistan/cap-feed/ru/atom.xml',
        lang='ru',
        notes='Official Uzhydromet CAP Atom feed hosted on the MeteoInfo alert platform, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='vmgd_cap',
        name='Vanuatu Meteorology and Geo-Hazards Department CAP Feed',
        backend='generic_cap',
        country_code='VU',
        url='https://cap-sources.s3.amazonaws.com/vu-vmgd-en/rss.xml',
        lang='en',
        notes='Official Vanuatu Meteorology and Geo-Hazards Department CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='zmd_cap',
        name='Zambia Meteorological Department CAP Feed',
        backend='generic_cap',
        country_code='ZM',
        url='https://zmd.gov.zm/api/cap/rss.xml',
        lang='en',
        notes='Official Zambia Meteorological Department CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='weatherzw_cap',
        name='Meteorological Services Department of Zimbabwe CAP Feed',
        backend='generic_cap',
        country_code='ZW',
        url='https://www.weatherzw.org.zw/api/cap/rss.xml',
        lang='en',
        notes='Official Meteorological Services Department of Zimbabwe CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='saint_lucia_cap',
        name='Saint Lucia Meteorological Service CAP Feed',
        backend='generic_cap',
        country_code='LC',
        url='https://saint-lucia.cap-composer.wiscaribbeancmo.org/api/cap/rss.xml',
        lang='en',
        notes='Official Saint Lucia CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='do_indomet_es',
        name='Instituto Dominicano de Meteorología CAP Feed (Spanish)',
        backend='generic_cap',
        country_code='DO',
        url='https://cap-sources.s3.amazonaws.com/do-indomet-es/rss.xml',
        lang='es',
        notes='Official Dominican Republic CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='ec_inamhi_es',
        name='Instituto Nacional de Meteorología e Hidrología CAP Feed (Spanish)',
        backend='generic_cap',
        country_code='EC',
        url='https://cap-sources.s3.amazonaws.com/ec-inamhi-es/rss.xml',
        lang='es',
        notes='Official Ecuador CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='sz_met_en',
        name='Eswatini Meteorological Service CAP Feed (English)',
        backend='generic_cap',
        country_code='SZ',
        url='https://cap-sources.s3.amazonaws.com/sz-met-en/rss.xml',
        lang='en',
        notes='Official Eswatini CAP RSS feed distributed via the WMO Alert Hub mirror, with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='cw_meteo_en',
        name='Meteorological Department Curaçao CAP Feed (English)',
        backend='generic_cap',
        country_code='CW',
        url='https://www.meteo.cw/rss/CAP_en.xml',
        lang='en',
        notes='Official Curaçao CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='cw_meteo_nl',
        name='Meteorological Department Curaçao CAP Feed (Dutch)',
        backend='generic_cap',
        country_code='CW',
        url='https://www.meteo.cw/rss/CAP_nl.xml',
        lang='nl',
        notes='Official Curaçao CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='cw_meteo_pap',
        name='Meteorological Department Curaçao CAP Feed (Papiamento)',
        backend='generic_cap',
        country_code='CW',
        url='https://www.meteo.cw/rss/CAP_pap.xml',
        lang='pap',
        notes='Official Curaçao CAP RSS feed with linked CAP XML and polygon geometry.',
    ),
    WarningSource(
        id='metservice_nz_cap',
        name='MetService New Zealand CAP Feed',
        backend='generic_cap',
        country_code='NZ',
        url='https://alerts.metservice.com/cap/rss',
        lang='en',
        notes='Official MetService public CAP alert RSS feed.',
    ),
    WarningSource(
        id='meteoalarm_atom_andorra',
        name='Meteoalarm Atom Feed (Andorra)',
        backend='meteoalarm_atom',
        country_code='AD',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-andorra',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_estonia',
        name='Meteoalarm Atom Feed (Estonia)',
        backend='meteoalarm_atom',
        country_code='EE',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-estonia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_slovenia',
        name='Meteoalarm Atom Feed (Slovenia)',
        backend='meteoalarm_atom',
        country_code='SI',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-slovenia',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_sweden',
        name='Meteoalarm Atom Feed (Sweden)',
        backend='meteoalarm_atom',
        country_code='SE',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-sweden',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_switzerland',
        name='Meteoalarm Atom Feed (Switzerland)',
        backend='meteoalarm_atom',
        country_code='CH',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-switzerland',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and verified polygon geometry.',
    ),
    WarningSource(
        id='meteoalarm_atom_ukraine',
        name='Meteoalarm Atom Feed (Ukraine)',
        backend='meteoalarm_atom',
        country_code='UA',
        url='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-ukraine',
        lang='en',
        notes='Official Meteoalarm Atom feed with linked CAP alerts and verified MultiPolygon geometry.',
    ),
)

SOURCE_BY_ID = {source.id: source for source in SOURCES}
